### ISSUE TITLE
Custom controllers

### ISSUE THREAD

**Issue by dftd** [mindstellar/Osclass#12]
Instead of adding custom controllers with "_osc_run_hook('custom_controller');_" which is called in _custom.php_ it would be awesome if in the _switch_ statement in _index.php_ we have something like this:

` case ('new_controller'):   // new controller `
    ` osc_run_hook('new_controller'); `
`  break; `

It's a very simple thing. One of the use cases is this one: I wanted a plugin that has custom controller for AJAX (I'm usually making plugins for Osclass in MVC pattern), but as "_osc_run_hook('custom_controller');_" is called in _custom.php_ controller, '_IS_AJAX_' was set to 0, meaning AJAX wouldn't work correctly. This gives us an option to make a controller from scratch.

Thanks, regards.

**Comment by dev-101** [comment]
Could be done. Nice idea ;)

**Comment by navjottomer** [comment]
Interesting will look into it. 
@dev-101 you can share if you have something for it.

**Comment by dev-101** [comment]
No, I initially thought there could be collisions if there are 2 controllers with the same name, but that shouldn't be common.

**Comment by webmods-croatia** [comment]
Would we need to modify osc_add_route() method or there is a parameter to define action?
