### ISSUE TITLE
Removal of languages from core bundle

### ISSUE THREAD

**Issue by navjottomer** [mindstellar/Osclass#128]
Removal of languages from osclass bundle will reduce current zip size.
Better if we use https://github.com/navjottomer/osclass-languages repository as the remote source.

**Comment by webmods-croatia** [comment]
@navjottomer I'm definitely interested in this. Will we use the same way as for locations (JSON)?

**Comment by navjottomer** [comment]
Yup, with a difference that we need to implement a upgrade method too.

**Comment by webmods-croatia** [comment]
@navjottomer I have a question that's somewhat related to this.

> Want to help create a pull request from you clone, just make sure of few things
> - Never target master-branch
> - Target develop branch if you wan't to merge your fixes.
> - Request a feature branch if your pull request change the functionality of our project.

So with future feature request related PR's (including this one), you need to make a separate branch? Or I target develop?

**Comment by navjottomer** [comment]
You can request a feature branch if you think it changes lot's of the files and hard to keep track of. Other developer or testers can also test your feature without the instability( or being highly active ) of the develop branch.
You can request a separate branch in your pull request( based on develop-branch) comment, It will be targeted to the new branch and merged so others can test your feature.
I hope it clarifies the intention for separate branches.

**Comment by webmods-croatia** [comment]
I have no idea how would language update work without overwriting the existing translations. How did Osclass do it? I never updated languages before...

**Comment by dev-101** [comment]
English can be included as a default / standard part, others can be downloaded later.
It may serve both as an example, and if it is default, maybe as a fallback (not sure).
This is how it was before.

**Comment by dev-101** [comment]
btw. offtopic about minor thing with naming convention of releases.
I think we should follow the old way.

NOW: **osclass-v3.9.0.zip**
BEFORE: **osclass_3.9.0.zip**

**Comment by dev-101** [comment]
> I have no idea how would language update work without overwriting the existing translations. How did Osclass do it? I never updated languages before...

Good point and I never used update feature myself (manual updates only). Files are easy to overwrite, but database (pages) can be tricky to restore for users with no sql knowledge.

**Comment by navjottomer** [comment]
We just overwrite the language files ( Only core translation files). Btw language upgrade is not a priority for now but we can start with functionality to download languages via our repo.

@dev-101 It's already renamed now. I created a script to use the tag name to create an installer archive, will change it to follow an old naming convention in next release.

**Comment by webmods-croatia** [comment]
@navjottomer Okay. Am I allowed to push the JSON file directly to master of Osclass-languages repo?

**Comment by navjottomer** [comment]
Yup, you are. BTW better if you can create a new working branch for yourself and than merge your changes to master branch. 

Read this for more information: [Collaborator access](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account)

**Comment by xiris** [comment]
I'm reviving this, did we have any progress on this?
I finished the composer integration, maybe we should add during the installation to download the languages or during the composer-install part. What do you think?

**Comment by webmods-croatia** [comment]
@navjottomer Close this.
