### ISSUE TITLE
Osclass search doesn't take relevance in account

### ISSUE THREAD

**Issue by navjottomer** [mindstellar/Osclass#129]
By default, Osclass search class make searches in boolean mode and doesn't take relevance into account.
 I am sure many have complained about it.

**Comment by webmods-croatia** [comment]
I ain't familiar with Osclass search and full text search in general. Mind to explain a bit?

**Comment by navjottomer** [comment]
I am not sure that I will be better than [MySQL Docs](https://dev.mysql.com/doc/refman/5.5/en/fulltext-search.html). 
Osclass search uses MySQL FullText functionality for its usage. When you search for any keyword in osclass site, It works like a grep command. 
For a very simple example, if you search for "car" in osclass, it will return a list of all items which have "car" keyword in their description ordered by publishing time. It doesn't take any account of how many times that keyword occurred in the description and that is not an expected behaviour to many.

**Comment by xiris** [comment]
Are you sure this a bug?
For me, it seems more of an improvement to the current behavior.
