### ISSUE TITLE
Breadcrumb uses deprecated URL for structured data

### ISSUE THREAD

**Issue by Netforza** [mindstellar/Osclass#178]
Breadcrumb uses 
http://data-vocabulary.org/Breadcrumb
which does not work any more.
Suggestion to remove it completely or switch to schema.org

**Comment by xiris** [comment]
Thanks for the feedback, will submit a PR and should be in the next release.

**Comment by eurobank** [comment]
Is that something easy we can manually do?
I have started to get warnings about it from Google webmaster service.

**Comment by webmods-croatia** [comment]
Fixed here: https://github.com/navjottomer/Osclass/pull/202/commits/ef47f93f314146f3ec5df39b0c447276bb4e39fd

**Comment by webmods-croatia** [comment]
@navjottomer Close

**Comment by eurobank** [comment]
Does the breadcrumb **plugin** suffer from this also?
