### ISSUE TITLE
Composer implementation

### ISSUE THREAD

**Issue by xiris** [mindstellar/Osclass#191]
This discussion was started here: https://osclass.discourse.group/t/composer-implementation/108/2

Moving to Github now as I expect to have more audience.
Please comment below if you have a different view or understanding and let’s make a great implementation.

There are many approaches we could follow. However, we should have different strategies for 3.x and 4.x (or any other name for future major version)

For the 3.x version and to keep backward compatibility, I think the best would be to:

- Remove libraries files from OSCclass repository
- Load libraries via composer
- Add composer call into Installer

For the 4.x version, we will probably have breaking changes as this will change the project structure.
The idea is to split the codebase, initially in 3 parts and independent repositories:

- Platform
- Core
- Admin
- Plugins

**Platform**
This is the entry-point in which people will use OSClass, install plugins, languages, etc.
The composer will know and load Core and Admin repositories.

**Core**
As the name says, it is the core of the system.
We basically move everything from /oc-includes/osclass to this repo.
As there is a lot of legacy, we need to map all the files to be able to autoload.

**Admin**
The admin part should have its own repository as well.

**Plugins**
We should have a better plugin system loaded via composer
Need to mature the idea and shouldn’t be in the initial release of version 4.

Lemme know your thoughts

**Comment by navjottomer** [comment]
Good to go.
