### ISSUE TITLE
Listing moderation as default feature in listing settings

### ISSUE THREAD

**Issue by mkraha** [mindstellar/Osclass#197]
If osclass 4 comes with default moderation options for listings it will be great and those options are already available as plugin named **More Edit** which is developed by osclass team itself.

**Comment by webmods-croatia** [comment]
I've never actually used that plugin as I heard it could interfere with some stuff. I'll check it out.

**Comment by mkraha** [comment]
The plugin for listings moderation. 
[Download](https://we.tl/t-7QhlDl1BFK) and try.

**Comment by mkraha** [comment]
Any update regarding this feature?

**Comment by webmods-croatia** [comment]
@RahaMK I checked the plugin, integrating its features in Osclass core shouldn't be a problem.
More info soon.

**Comment by dftd** [comment]
https://github.com/mindstellar/Osclass/pull/302
