### ISSUE TITLE
Routing and controllers

### ISSUE THREAD

**Issue by dftd** [mindstellar/Osclass#199]
Routes should either be connected straight up with controllers, instead of files, or there should be another function for routes that use the controller approach.

The process of making something like a callback or an AJAX handler page is ridiculous in Osclass...

Just a small example:

`osc_add_ctrl_route('payment-callback', 'payments/callback', 'payments/callback', 'PaymentController@CallbackHandler');`

**Comment by navjottomer** [comment]
See if recent changes are enough.

**Comment by dftd** [comment]
> See if recent changes are enough.

Looking good.
