### ISSUE TITLE
Jquery 1.8.0 to latest

### ISSUE THREAD

**Issue by fre2mansur** [mindstellar/Osclass#20]
Is it a good idea to update jquery?

**Comment by navjottomer** [comment]
It'll be updated, but need to check compatibility with old javascript code. Also, there are many themes and plugins which may break with this change. 
I'll keep it open until not fixed.

**Comment by fre2mansur** [comment]
I think we don't need to worry about themes and plugins, developer of plugin/theme should care about that. or we can update the free plugin and themes. but thank you.

**Comment by dimalif** [comment]
@fre2masur The thing is that some few free plugins and themes are discontinued and they will not be fixed by their original devs. 

For example i use osclasswizards theme and those guys got off the train. Also i can't live without the antispam/duplicates plugin that some guy (liath) made 1-2 years back. He is also missing. That particular plugin already broke with this github version.

**Comment by fre2mansur** [comment]
@dimalif osclasswizards is commercial theme we cant do anything. if antispam/duplicates plugin is free i can make support of this github version. but not now. once we got a major or stable update from this fork then we can fix the plugins and theme to support this fork.

**Comment by dimalif** [comment]
Nope, OsclassWizards is a FREE plugin. Soon to be moved to github, as per OsclassWizards statements after closing down.

**Comment by mkraha** [comment]
> 
> 
> It'll be updated, but need to check compatibility with old javascript code. Also, there are many themes and plugins which may break with this change.
> I'll keep it open until not fixed.

Now, breaking changes needs for Osclass and core should be updated also theme and plugin developer will be do the same.

**Comment by mkraha** [comment]
> 
> 
> Is it a good idea to update jquery?

+10

**Comment by navjottomer** [comment]
Fixed 
7d0ef1fe81b7fd497eaf655ee99fab22caad3a49
5322ec67c231b639598e58d7026a2082ec64c574
9631c8bb9daa5ba6e39b667b911ca2607e4c7a52
bd654e687c1b2e1772e46c69dfa7fcf7f4bca609
