### ISSUE TITLE
Problems with osclass 3.9 in php 7

### ISSUE THREAD

**Issue by DonDominios** [mindstellar/Osclass#200]
debug file shows this same error many times

PHP Warning:  A non-numeric value encountered in
/oc-includes/osclass/classes/Pagination.php on line 52
/oc-includes/osclass/classes/Pagination.php on line 53

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in
/oc-includes/osclass/model/Search.php on line 786
/oc-includes/osclass/model/Search.php on line 790
/oc-includes/osclass/model/Search.php on line 794
/oc-includes/osclass/model/Search.php on line 798
/oc-includes/osclass/model/Search.php on line 802

can someone tell me how to correct it?

**Comment by webmods-croatia** [comment]
Warning, not an error... It's not a real problem.

Which exact PHP version you use? 7.*?

**Comment by DonDominios** [comment]
7.3 but it is a great nuisance to receive these messages in the site log

**Comment by eurobank** [comment]
They are not in the site log (there is no such thing), they appear in debug.log IF debug mode is enabled.

**Comment by DonDominios** [comment]
A non-numeric value encountered" in PHP 7.4 
oc-includes/osclass/classes/Pagination.php on line 52
oc-includes/osclass/classes/Pagination.php on line 53
how to correct this problem?

**Comment by eurobank** [comment]
A non-numeric value encountered oc-includes/osclass/ItemActions.php on line 1746

Osclass 3.9, PHP 7.3
