### ISSUE TITLE
Osclass Breadcrumb Showing Wrong Region 

### ISSUE THREAD

**Issue by mcasaccio** [mindstellar/Osclass#205]
Osclass breadcrumb showing wrong Region in City page

Listing is posted to Santa Fe/Rosario,

But it’s showing Cordoba/Rosario

Two region have same cities. How to show exact Region?

When there are 2 or 3 same city names in different regions, the proper city to the corresponding region is not shown.

Reference https://clasificadosplus.com/rosario-c49759

Can someone tell me how to fix it?

/oc-includes/osclass/classes/Breadcrumb.php line:190

$aRegion = Region::newInstance()->findByPrimaryKey($aCity['fk_i_region_id']);

**Comment by navjottomer** [comment]
You can change your city slug. There is no other fix right now.

**Comment by Nomak-** [comment]
> You can change your city slug. There is no other fix right now.

I had to change the city name from mysql (do not modify the slug)
