### ISSUE TITLE
Fatal error core osclass category

### ISSUE THREAD

**Issue by abdulghanysyed** [mindstellar/Osclass#217]
Anyone please help me to resolve This issue..

17-Apr-2020 13:00:02 Asia/Kolkata] PHP Fatal error: Uncaught Error: Call to a member function numRows() on boolean in /public_html/oc-includes/osclass/model/Category.php:127 Stack trace: 
#0 /public_html/oc-includes/osclass/model/Category.php(207): Category->listWhere('b.s_name != '' ...') 
#1 /public_html/oc-includes/osclass/model/Category.php(232): Category->listEnabled() 
#2 /public_html/oc-includes/osclass/model/Category.php(73): Category->toTree() 
#3 /public_html/oc-includes/osclass/model/Category.php(40): Category->__construct('en_US') 
#4 /public_html/oc-includes/osclass/model/Search.php(729): Category::newInstance()
 #5 /public_html/oc-includes/osclass/controller/search.php(312): Search->addCategory('219')
 #6 /public_html/index.php(102): CWebSearch->doModel() 
#7 {main} thrown in /public_html/oc-includes/osclass/model/Category.php on line 127

**Comment by webmods-croatia** [comment]
@navjottomer "Call to a member function numRows() on boolean" is the error that I encountered many times myself, through many different cases. It's not descriptive at all, something that should be fixed.
I don't think it should give a fatal error, maybe just a warning and return array also?

**Comment by dev-101** [comment]
Could be that SQL server stopped/crashed/timed-out and return value (object/array) that was expected wasn't, as SQL many times returns nothing, so PHP tries to interpret it in a meaningful way.

You need to debug this in the code to see what the returned value actually is (most likely nothing / null or 0 interpreted as boolean), and why (if it happens regularly, could be slow server/query, or some changes you did, slow function, plugin, cron etc.).

**Comment by navjottomer** [comment]
It is nothing to do with numRows() method. This error simply means you're trying to call a method on boolean value. 
This means that we didn't check the validity of our object while using it as an object. This is a fatal flaw.
The above method should only be called on DBRecordsetClass object.
