### ISSUE TITLE
 develop branch osclass_autoloader error 

### ISSUE THREAD

**Issue by web-media** [mindstellar/Osclass#218]
Develop branch osclass_autoloader  block another autoloader (from theme or plugins ) by   throwing  new RuntimeException 

1. register another autoloder in a plugin '...'
2. See error

**Comment by navjottomer** [comment]
Namespacing can fix that but will break almost every plugin and themes, need to think of a new approach for that.

**Comment by web-media** [comment]
just remove this line this will allow other autoloader to work .. 
 when runtime if that file do not exist there will be a  fatal error .. class not found .
there is no need to throw that error in  osclass autoloader
 // throw  new RuntimeException("AutoLoad Error: No file found. $fullFile");
```php
function osc__loadIfExists($filename)
{
    $fullFile = __DIR__ . '/' . $filename; // its relative to this path

    if ((@include $fullFile) === false) {

     // return false;
    }
	//return true  ;
}
```

**Comment by navjottomer** [comment]
@web-media make a pull request I'll merge it.

**Comment by navjottomer** [comment]
#223 fixes this issue.
