### ISSUE TITLE
Item phone field

### ISSUE THREAD

**Issue by webmods-croatia** [mindstellar/Osclass#219]
This should be added once and for all... No need for a million various phone plugins.

**Comment by fre2mansur** [comment]
Do you mean a special phone number for an item? like, unregister users using contact name?

**Comment by webmods-croatia** [comment]
> Do you mean a special phone number for an item? like, unregister users using contact name?

Something like contact name & email, yes. s_contact_phone
It gets prefilled with the user phone (if available) but can be changed.

**Comment by webmods-croatia** [comment]
That's for another feature request, but phone number login should be added as well.

**Comment by webmods-croatia** [comment]
Due to various number types, the input type should be text. On the backend, we can check if it contains text and throw an error then.
Format validation can be done on the frontend and it's theme developer related.

Once we enhance the Form classes, **inputmode="tel"** should be added to show a proper keyboard on mobile devices.
