### ISSUE TITLE
init_admin hook run twice on any settings controller

### ISSUE THREAD

**Issue by web-media** [mindstellar/Osclass#225]
**Describe the bug**
init_admin hook run twice on settings controller. 

**To Reproduce**
1. create a   function 
```php 
function test_init (){
      echo' test_admin';
  }
```
2. add  the function to init_admin hook in theme function file or any  active plugin
```php
osc_add_hook('init_admin', 'test_init');
```
3. go to   any settings page in admin
4.  inspect page  source code 
``` php
<body class="compact" cz-shortcut-listen="true">test_admin test_admin
```

**Comment by navjottomer** [comment]
@web-media 
I only found two instances of `osc_run_hook('init_admin');` in this case, this is the file which is creating this issue. https://github.com/mindstellar/Osclass/blob/206211cd2af5660a06bacbf58bb10c9a9d8e91f5/oc-includes/osclass/classes/controller/base/AdminSecBaseModel.php#L45

Problem is with `AdminSecBaseModel.php` file as it is extended with **main setting class** and the **child setting class** which in turn runs this hook twice.

To check yourself change this in AdminSecBaseModel.php
```php
osc_run_hook('init_admin');
```
to 
```php         
$class_name = get_called_class();
osc_run_hook('init_admin', $class_name);
```
and modifiy your function `test_init` function like:
```php
function test_init ($class_name){
    echo $class_name;
}
```
This will print the class name in which this hook is called.

To fix this we can limit all hooks to run only once or we can restrict this hook only. 
Please share your suggestion?

**Comment by navjottomer** [comment]
@web-media pushed to develop branch with #225, please check, I hope it will fix this issue. If this can be improved please make a pull request.
@webmods-croatia close if it is okay.

**Comment by web-media** [comment]
@navjottomer  , @dev-101 
i don't see the need of checking of previous run of every hook.
A hook can run twice if developer erroneously type osc_run_hook ('hook') twice , include a file twice where a hook will run ( header,footer )...
 But  possibility to check if a hook had run is a good addition !
In our case 
CAdminSettings (has no constructor) extends AdminSecBaseModel 
    => CAdminSettings  will call parent constructor(AdminSecBaseModel )  first time
inside do model will bring another class witch extends AdminSecBaseModel 
```php
 case('comments_post'):
                require_once(osc_admin_base_path() . 'controller/settings/comments.php');
                $do = new CAdminSettingsComments();
                break;
```
class CAdminSettingsComments (has no constructor) extends AdminSecBaseModel 
    => CAdminSettingsComments  will call parent constructor AdminSecBaseModel second time

**Comment by web-media** [comment]
prepared the pull request .. just finishing touches

**Comment by navjottomer** [comment]
I merged the pull request, but it'll not fix the the double run of hooks in admin settings, we also need to add checks in those controllers.
