### ISSUE TITLE
Rename vendor folder on install

### ISSUE THREAD

**Issue by maddrid** [mindstellar/Osclass#228]
Renaming vendor folder   on install or place some info  into  docs  .
Malware scan vendor folder for vulnerable  files .

**Comment by webmods-croatia** [comment]
Not fully related to this, but in the future, we should use a similar structure as Laravel does.

https://devdojo.com/articles/explaining-the-laravel-public-folder

> By having all the functionality of our application outside the root folder of the website we won't have to worry about a lot of the common vulnerabilities people commonly have on their website. Since all the functionality/files are one folder above the root folder they can never be accessed by the end-user and is only available to the application. Thanks Laravel for the awesome security :)

**Comment by eurobank** [comment]
@webmods-croatia 

I think this is a bad idea, since files outside the folder of the site (sometimes) have/need special permissions to be accessed by files INSIDE the folder of Osclass. 

That will create more problems and i have never seen that in other scripts like Wordpress for example.
