### ISSUE TITLE
Sign up and Login with phone number 

### ISSUE THREAD

**Issue by Janethjepkogei** [mindstellar/Osclass#229]
My users can't sign up or login to my platform because they don't have email accounts. Forcing them to create emails.

Allowing them to use phone number instead of email to sign up and login would solve this issue as all my users have phone numbers

**Comment by navjottomer** [comment]
We do not have any open-source SMS API to validate phone numbers. A simple plugin can easily provide this feature by using any 3rd party paid SMS API.
In future, we will provide a social login feature in osclass which will provide an option to signup if they have an account on popular social sites.

**Comment by oqueface** [comment]
> My users can't sign up or login to my platform because they don't have email accounts. Forcing them to create emails.
> 
> Allowing them to use phone number instead of email to sign up and login would solve this issue as all my users have phone numbers

Hello 

> My users can't sign up or login to my platform because they don't have email accounts. Forcing them to create emails.
> 
> Allowing them to use phone number instead of email to sign up and login would solve this issue as all my users have phone numbers

Hello Janeth,

Did found a solution for that?
