### ISSUE TITLE
New auto-update branch 

### ISSUE THREAD

**Issue by navjottomer** [mindstellar/Osclass#233]
Added a new branch 'auto-update' ( anyway it's temporary).
Added some utility classes and basic upgrade class to auto-update osclass from this repository.
Not completed, not everything tested either need help in that.
@web-media @webmods-croatia @dev-101 
With current implementation this will work.
```php
use mindstellar\osclass\classes\utility\Upgrade;
$upgradeOsclass = new Upgrade();
$upgradeOsclass->doUpgrade();
```

**Comment by web-media** [comment]
Hy . What's the road map  of this branch or develop branch ? 
Do we drop support for 3.8.0 , 3.9.0 and rewrite develop as non backwards compatible ?

**Comment by navjottomer** [comment]
@web-media Roadmap in this branch is to test/develop the auto-upgrade system to work properly. Currently, it's in infancy and I have not provided any GUI handle to support auto-update. Created a separated branch so everyone can collaborate and can make changes if needed.
It will be merged into the develop branch when the update feature is ready.

**Related to develop branch:**
- Still needs to fix so many reported issues.
- We will not drop support for 3.9.0 yet, they will be upgradeable to next versions till 5.x.x, we drop support for 3.x.x in 5.x.x.
- In the first 4.x.x, release auto-update system must work, so we can push minor, major release efficiently. 
- For backward compatibility in 4.x.x we will try not to break compatibility(Core PHP dependency, no guarantee for core javascript and composer libraries) as much as possible with plugins and themes developed for 3.8.0 or 3.9.0. We will also provide new methods which developers can use in the meantime.
- It's not good to make any change in osclass which requires drastic changes in old themes and plugins, that will waste everyone's time.

That's it I guess.
