### ISSUE TITLE
PHP Warning:  array_merge()

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#242]
**Describe the bug**

From debug log

[22-May-2020 02:18:08 America/Los_Angeles] PHP Warning:  array_merge(): Argument # 2 is not an array in /home/public_html/oc-includes/osclass/utils.php on line 1678

**To Reproduce**

I think some plugin is doing a cleanup of files, removing files from directories or something like that. Not sure if this could come from a plugin?

Osclass 3.9 and PHP 7.2.x

**Comment by navjottomer** [comment]
This won't be fixed, we are introducing new functions for the same functionality. This function will be deprecated.

**Comment by eurobank** [comment]
Do you know if this breaks something or it is mostly harmless?

**Comment by navjottomer** [comment]
It is mostly harmless. It will be deprecated with a new function and a warning will trigger in logs if someone use this function.

**Comment by eurobank** [comment]
Well it is not harmless at all, in two plugins the files/directories can't be removed. 

So both plugins are useless and since their dev is MIA, there is no way to fix that.

**Comment by navjottomer** [comment]
replace existing `rglob` function with this code and your plugin will work, I will provide a better alternative in new FileSystem Class
```php
function rglob($pattern, $flags = 0, $path = '')
{
    if (!$path && ($dir = dirname($pattern)) !== '.') {
        if ($dir === '\\' || $dir === '/') {
            $dir = '';
        }
        return rglob(basename($pattern), $flags, $dir . '/');
    }
    $paths = glob($path . '*', GLOB_ONLYDIR | GLOB_NOSORT);
    $files = glob($path . $pattern, $flags);
    foreach ($paths as $p) {
        $files = array_merge($files, rglob($pattern, $flags, $p . '/'));
    }
    return $files;
}
```

**Comment by eurobank** [comment]
Will do and update here, thanks

**Comment by eurobank** [comment]
Thanks @navjottomer god bless you man!

I have no idea what we would do without your 3.9 work.
