### ISSUE TITLE
Missing country (Bulgaria)

### ISSUE THREAD

**Issue by arcsales** [mindstellar/Osclass#252]
I just downloaded the latest stable version (3.9) and went trough the standard installation.
When requested to point to country where the website will be targeting i notice that Bulgaria is missing from the list of options.

By they what does the script do when choosing different locations?

**Comment by webmods-dev** [comment]
@navjottomer We should update the list completely with data from some trusted geo database...

**Comment by arcsales** [comment]
Thank you.
By the way does it matter what target country is chosen?

**Comment by navjottomer** [comment]
@webmods-dev
Sorry for a late reply, caught up between other things. Please check this project https://github.com/dr5hn/countries-states-cities-database it can be a better alternative for our sources.

@arcsales Explain?

**Comment by arcsales** [comment]
Yes please. What is different that the script do when chosen different country?
Is all about countries, cities and languages or there are more stuff done by the script behind the scenes?
Im old user of osclass but never though about it till now :D

**Comment by navjottomer** [comment]
It will just create those locations nothing more it'll do.

**Comment by arcsales** [comment]
Oh okay. Thank you!

**Comment by pipetko** [comment]
> @webmods-dev
> Sorry for a late reply, caught up between other things. Please check this project https://github.com/dr5hn/countries-states-cities-database it can be a better alternative for our sources.
> 
> @arcsales Explain?

How to use it ? I am sorry for the dummy duestion, but I am newbie

**Comment by arcsales** [comment]
That is a complete list of all countries, regions/states and cities.
You can import desired country from the package and import it to your website. It will save you time.
I dont think is ready to go for osclass but at least you have them all at the same place and you can play with them.

**Comment by webmods-dev** [comment]
@navjottomer Ideally, we would want a complete new location database. However, for existing sites migrating to 4.0, It'll be a problem as region/city IDs will be changed.

One option might be to make a migration script to update the IDs based on region/city name, but in some cases it can't be accurate.

What are your thoughts? I work on this ASAP, once I get a response.

**Comment by navjottomer** [comment]
@webmods-dev 
I have created a new repository at https://github.com/mindstellar/geodata with the newly updated source. Did not get the time to implement that in Osclass (Still busy with the core ). Have a look at that new repo and let me know how can I help you with that data.

**Comment by webmods-dev** [comment]
> We want to migrate that old data with the new one a migration script can work.
> I have created a new repository at https://github.com/mindstellar/geodata with the newly updated source. Did not get the time to implement that in Osclass (Still busy with the core ). Have a look at that new repo and let me know how can I help you with that data.

Why CSV instead of SQL?

**Comment by navjottomer** [comment]
CSV is a clean source to make something compatible with osclass. Original data at /dr5hn/countries-states-cities-database wasn't clean, I had to clean it before we can use or anyone work on that.
On that repo, we need scripts to take that data and make compatible SQL files ( or something else if you need) to feed in osclass.

@webmods-dev can you skype me, so we can keep in touch.

**Comment by navjottomer** [comment]
Fixed in https://github.com/mindstellar/Osclass/commit/9bddfea5c958c0ea630d76f65221e6c75e316e89
