### ISSUE TITLE
User Settings - Ban of names not working

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#255]
**Describe the bug**

In User Settings the ban words in users names do not work since 3.8

**To Reproduce**
Put in there some user ids like "admin,user,sex,dating" and make an account. Account is allowed. You can create for example a user named "user".

Also it would be nice if * filtering was allowed (like * sex *).

**Comment by navjottomer** [comment]
show the results of 
```php 
getPreference('username_blacklist');
``` 
or you can check this in `t_preference table`

**Comment by eurobank** [comment]
Here is what i have, tried everything, doesn't work.

![Screenshot](https://user-images.githubusercontent.com/4467158/87421834-40e02900-c5e0-11ea-904e-95efa17c6255.png)

**Comment by navjottomer** [comment]
I checked again and this is working fine in our development branch, so closing it down for now.
