### ISSUE TITLE
When searching by prices, for the maximum price it is possible to enter only a number with 5 zeros.

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#257]
**Describe the bug**
Hi! When searching by prices, for the maximum price it is possible to enter only a number with 5 zeros. This may not be enough when looking for properties that have higher prices.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by navjottomer** [comment]
Please see this for the fix.
https://github.com/mindstellar/theme-bender/commit/71dfaf3876d4989c3c6c62318c9953610036ed78

**Comment by alex7070m** [comment]
Thanks! It works!
