### ISSUE TITLE
Keyword search by relevance

### ISSUE THREAD

**Issue by Tangol** [mindstellar/Osclass#260]
I've tested the [keyword sort by relevance](https://github.com/mindstellar/Osclass/commit/d097fabf326b5788c17312b08b8ee679bbc22c88) on the latest [dev branch](https://github.com/mindstellar/Osclass/commit/c8c438c9e2790fbce1a564951865a77b038a59f4) and found it to be a bit unreliable.

What I did:
1. Created an account and posted an add "**Mercedes Vito**" (**vito** is the keyword that appears only 2 times in this listing - title and body).
2. Logged out and posted another 2 unauthenticated adds like in the screenshot below.
3. Search for "**vito**", sort by **Relevance** - result:
![vito1](https://user-images.githubusercontent.com/3336728/89450709-a187ff00-d763-11ea-9190-8a8d3aaa6ff5.jpg)

4. Logged back in and edited the title of my first add from "Mercedes Vito" to "**Mercedes**".
5. Search for "**vito**", sort by **Relevance** - result:
![vito2](https://user-images.githubusercontent.com/3336728/89451056-46a2d780-d764-11ea-8874-e86a7e02915f.jpg)

As you can see, the listing remains on top, with the script still considering it the most relevant, even though the keyword appears only once in the body.

What do you think?

**Comment by navjottomer** [comment]
Interesting! What is your storage engine on `oc_t_item_description` table?

**Comment by Tangol** [comment]
![sengine](https://user-images.githubusercontent.com/3336728/89454849-fd558680-d769-11ea-9911-32bf8b8b29de.jpg)

That's weird. Why MyISAM only for this table?

**Comment by navjottomer** [comment]
Oops, its legacy, previously InnoDB engine doesn't have a full-text search feature. But it is well supported in MySQL 5.7 and later.
My installation does have a description table in InnoDB engine that's why it was working fine when I tested. With MyISAM tables, ranking is not that reliable (ranker return only integer value instead of float in InnoDB). 
I'll submit a patch to use InnoDB as the default engine.

**Comment by navjottomer** [comment]
With the new patch, it'll work with MyISAM tables too, till we will not migrate old installation to InnoDB table engine (Which is still better);
I am closing it for now.
