### ISSUE TITLE
Choice of currency when searching by prices

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#262]
**Is your feature request related to a problem? Please describe.**
Hello! It would be nice to have the opportunity to choose a currency when searching by prices

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by webmods-dev** [comment]
There was a plugin for this, but it only searched ads that had a specific currency, for example, USD. If there were ads in EUR which matched the defined price range, it wouldn't show them.
The plugin didn't "know" how to convert the prices.

It's possible to implement this with some sort of currency rates API.

@navjottomer your thoughts?

**Comment by navjottomer** [comment]
Osclass does provide necessary methods to implement this. Not everything has to be implemented in osclass core.
