### ISSUE TITLE
Convert png files uploaded by users to jpg

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#265]
**Is your feature request related to a problem? Please describe.**
Hello! it happens that users upload png images, often large (several megabytes). These pictures are not reduced in size during processing, unlike jpg. Therefore, it would be good if png images are converted to jpg so that they can be reduced in size when processed in osclass.

**Comment by navjottomer** [comment]
There is already an option to force a jpeg extension in media settings.
