### ISSUE TITLE
The ability to add a custom field - number type

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#266]
**Is your feature request related to a problem? Please describe.**

Hello! It would be nice if the admin could add a custom field - type number. This is necessary for example to display the proposed salary in the "Job" category and the ability to search by this parameter (the proposed salary).

**Comment by navjottomer** [comment]
I have some plans with the custom field in future, I am sure that will has this kind of field. It is hard to comment when I am pretty much all occupied with other osclass stuff right now.
The current priority is to finalize the current dev branch and launch a new beta release of osclass.

**Comment by dftd** [comment]
@navjottomer Any info on this in 5.0?

**Comment by navjottomer** [comment]
Took a bit more time, You can go-ahead now

**Comment by dftd** [comment]
@navjottomer The latest develop branch has some problem with extending custom fields.

When I click on "+" button to show a form to add a field, it just freezes and my debug log is spammed with this:

> Undefined index: s_name in osclass-mindstellar/oc-includes/osclass/classes/model/Field.php on line no 137 Error Code:8

In the end apache just crashes.

**Comment by dftd** [comment]
Can close this? Or we're just adding labels now?

**Comment by navjottomer** [comment]
It's better to have these labels till not merged in main branch. Easier to
know what fixed in developer branch.
