### ISSUE TITLE
When trying to install the vQmod plugin, the site gives an error http 500

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#267]
**Describe the bug**

Hello! When trying to install the vQmod 1.2.2 plugin, the site gives an error http 500. I use PHP 7.4, Osclass 3.9

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alex7070m** [comment]
During installation, there was a message that VQMOD 2.6.4 is being installed
![11082020](https://user-images.githubusercontent.com/69157204/89918840-3460e780-dc03-11ea-8e39-b715fcab09b8.jpg)
![11082020-1](https://user-images.githubusercontent.com/69157204/89918863-3c208c00-dc03-11ea-913b-2e2a67f25196.jpg)

**Comment by navjottomer** [comment]
It should be handled through plugin dev, nothing we can do with it. Due to the changes we are making with osclass, it would be hard for a plugin developer to make a compatible vqmod plugin for next 1-2 osclass release.
BTW we don't even recommend to rely on such a mod.
