### ISSUE TITLE
Sequential selection of the main category first, and then the subcategory when submitting an ad in the Bender theme.

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#268]
**Is your feature request related to a problem? Please describe.**

Hello! It would be convenient for users to first select the main category and then select a subcategory from the list. Nowadays, if there are many subcategories, it can be difficult for a user to find the required subcategory from a large list.

It would be nice if the  red button  "Publish your ad for free" was at the top of the site not only in the desktop version of the site, but also in the mobile version.

Thanks

**Comment by webmods-dev** [comment]
@alex7070m This is a theme issue and it depends on theme developers.
Some themes have different category selects, just like the "Publish your ad" button.

If you want to contribute to the Bender theme (default one), please do it on this repo: http://github.com/mindstellar/theme-bender
