### ISSUE TITLE
Opening site in new window (blank) using a custom field URL.

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#270]
**Is your feature request related to a problem? Please describe.**

Hello! It would be nice to have sites open in new window (blank) when using a custom field URL.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by webmods-dev** [comment]
https://github.com/mindstellar/Osclass/issues/53
https://github.com/mindstellar/Osclass/pull/62

@navjottomer Shall we close this, or do I provide a better pull request with a filter - as you said?

**Comment by alex7070m** [comment]
Do what you think is right. But I think that links to user sites URL are better to open in a new window.

**Comment by navjottomer** [comment]
> #53
> #62
> 
> @navjottomer Shall we close this, or do I provide a better pull request with a filter - as you said?

@webmods-dev I think it's better to use a filter. In some cases, people may want the redirect to the new link in same page.

**Comment by alex7070m** [comment]
Thanks, does this filter already exist or are you just planning to implement it?

**Comment by webmods-dev** [comment]
@navjottomer I think it's best to have this integrated into Osclass. Do I add a setting per each custom field or a general one for each file?

@alex7070m We have to implement it. In case you want something like this on your site now, check the changes [here](https://github.com/mindstellar/Osclass/pull/62/commits/620fbae299045d3a39c2cba37a3001928f58d4d5) and replicate them in your installation.

**Comment by alex7070m** [comment]
I changed the file as You wrote , but the site still opens in the same window. Am I wrong with the changes? Maybe you have a ready corrected file?

**Comment by webmods-dev** [comment]
> I changed the file as You wrote , but the site still opens in the same window. Am I wrong with the changes? Maybe you have a ready corrected file?

Do you have any plugin that might affect custom field values?

**Comment by alex7070m** [comment]
Here are my plugins.

Can be viewed on the website  https://999-ru.com/vse-dlya-detej/detskaya-obyv/%d0%9e%d0%91%d0%a3%d0%92%d0%ac-%d0%9e%d0%a0%d0%a2%d0%9e%d0%9f%d0%95%d0%94%d0%98%d0%a7%d0%95%d0%a1%d0%9a%d0%90%d0%af-23-105_i39


![27082020-1](https://user-images.githubusercontent.com/69157204/91440042-a7f72b80-e876-11ea-8395-ff3b829b1ab7.jpg)

**Comment by eurobank** [comment]
Apparently this was never added? Any plans? For both custom fields AND links IN TinyMCE?

**Comment by dftd** [comment]
> Apparently this was never added? Any plans? For both custom fields AND links IN TinyMCE?

Nope. :/

For custom fields you can use this https://github.com/mindstellar/Osclass/commit/620fbae299045d3a39c2cba37a3001928f58d4d5

For TinyMCE, this option should be added to the init function: `default_link_target: "_blank"`

**Comment by eurobank** [comment]
Why not?

And for Tinymce, what i have found is

**extended_valid_elements : "a[href|target=_blank|rel=nofollow]",**

is that different?

**Comment by dftd** [comment]
@eurobank Both would probably work, I saw that in a quick Google search as well.

Navjot said we should make it optional with some filters or whatever, that's why it wasn't implemented yet.

**Comment by eurobank** [comment]
@dftd Is there a way, a filter, some hook, some function (you know all that, i do not), that we can use to open every outgoing link to a new window and nofollow, for posted ads and also for custom fields?
