### ISSUE TITLE
Confirmation of the phone number via SMS or a call using special services.

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#271]
**Is your feature request related to a problem? Please describe.**

Hello! It would be nice if the function of confirming the phone number via SMS or a call using special services was implemented. Otherwise, on the site will inevitably be abused by unscrupulous users with phone numbers. I heard that somewhere there is such plugin, but I think that this function is very important and it is better to have it already built into osclass.

**Comment by navjottomer** [comment]
Nope, it should be handled via a plugin. Osclass provides necessary hooks to implement this functionality.

**Comment by alex7070m** [comment]
Thanks, where can this plugin be found? I did not notice it on the site market.osclasscommunity.com

**Comment by webmods-dev** [comment]
> Thanks, where can this plugin be found? I did not notice it on the site market.osclasscommunity.com

I won't post links to other markets and whatnot here. If needed, a custom plugin can be developed. Otherwise, a quick Google search may lead you to some existing paid plugins.

**Comment by alex7070m** [comment]
Probably there are such plugins in other osclass market. But now there are different branches of osclass (osclass evo for example) and I'm not sure about the compatibility. For example, I know that in osclass evo many old plugins do not work.
