### ISSUE TITLE
Automattic Item Title 

### ISSUE THREAD

**Issue by isharaniro** [mindstellar/Osclass#273]
Is there way to generate item title automattically using custom field data and time,location data instead of user typed item title? 
i have seen some classified listing sites use that feature so items are well organized and it is favourable for serach results.
Thanks

**Comment by fre2mansur** [comment]
> this should developed be as a plugin . There is enough hooks to modify the item title on the fly ,and this require database models too .
> 
> ```
> ItemActions->add
>  $aItem       = osc_apply_filter('item_add_prepare_data', $aItem);
>  osc_run_hook('pre_item_add', $aItem, $flash_error);
>         $flash_error = osc_apply_filter('pre_item_add_error', $flash_error, $aItem);
> ItemActions->edit
>  $aItem       = osc_apply_filter('item_edit_prepare_data', $aItem);
> ```
> 
> ...... ... ...

How to use this?
