### ISSUE TITLE
disable admin language  ( develop )

### ISSUE THREAD

**Issue by maddrid** [mindstellar/Osclass#279]
**Describe the bug**
disabling admin language on admin  does not take effect . Language still active . see picture 

**To Reproduce**
1. Go to admin
2. Click deactivate language

**Expected behavior**
default Language should appear

**Screenshots**
![Language](https://user-images.githubusercontent.com/5124319/90979365-df06cd80-e554-11ea-9e76-1e27614331cc.PNG)

**Comment by navjottomer** [comment]
@maddrid I checked it and indeed it's an issue but we don't save any default language in osclass.
We can go with this in two different ways:
First is to give an option to make language primary and disable the option for deactivating and deleting the primary language.
The second is a bit easier to implement by giving a warning that disabling the active language will log you out from the current session and sign out the current user if he wishes to do so. 

What do you think?

**Comment by navjottomer** [comment]
@maddrid any thought ???

**Comment by maddrid** [comment]
As English  is primary before installing any language : 
when a language is disabled for admin then English should become  primary language. 
English should not be deleted  from admin

**Comment by navjottomer** [comment]
The new release branch doesn't have this issue. Working as expected.
