### ISSUE TITLE
The ability to display languages ​​on the site in the form of flags.

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#282]
**Is your feature request related to a problem? Please describe.**

Hello!
It would be nice, stylish and pleasant for visitors to display languages on the site in the form of flags, as is done on most sites on the Internet.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by webmods-dev** [comment]
The ability is there. It's for the theme developers to use it or not.
Same as for some of your previous questions.

I suggest you post such theme-related stuff on one of our forums (https://forums.osclasscommunity.com/ - my forum, https://osclass.discourse.group/ - official forum) and we can help you implement the requested features in your theme.
