### ISSUE TITLE
Incorrect User items number

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#283]
This is a very old problem with Osclass. There is also  a small plugin that fixes it (from dev101 i think).

Any ideas if this has been addressed in code **AFTER** 3.9 release?

**Comment by navjottomer** [comment]
How to reproduce it.

**Comment by eurobank** [comment]
Well i can't tell you how to replicate it. 

What happens is the number of user items in the column of admin/users is different from the actual number of users (shown in his profile list).

Here is the plugin from dev101 & Teseo 

Plugin will re-calculate all user's active items and correct the potentially wrong stats numbers in case you have experienced this issue. Additionally, it will add a new 'Total Items' column in Admin Dashboard > Users menu.

[1565208769-user_items_counter_200.zip](https://github.com/mindstellar/Osclass/files/5158410/1565208769-user_items_counter_200.zip)

**Comment by dev-101** [comment]
As I mentioned a number of times before, this is not related to the Osclass core.
You use some plugins that are doing this, it's not Osclass's core fault.
Given the fact most devs are no longer actively developing, your only chance fixing this is either by yourself or hiring developer. It's not easy to find one, though, there are only handful of them left working on this script... for how long, that's a million $ question.
