### ISSUE TITLE
Cambodia Import location Not correctly 

### ISSUE THREAD

**Issue by Bru-osclass** [mindstellar/Osclass#288]
**Describe the bug**

**To Reproduce**
1. Go to 'install osclass and then choose Cambodia for location or import it from admin panel'
2. Click on ‘Cambodia county '
3. Scroll to Region and show only Phnom  penh 
4. See error no other region And city like in  location list From 

https://github.com/mindstellar/geodata/blob/master/csv/KH-Cambodia.csv

This .csv is correct location

Please help to correct it

**Comment by navjottomer** [comment]
These locations are not finished yet and need time.

**Comment by Teurn** [comment]
Thank you so much, don't forget add it to import from repo like language

**Comment by navjottomer** [comment]
Fixed in https://github.com/mindstellar/Osclass/commit/9bddfea5c958c0ea630d76f65221e6c75e316e89
