### ISSUE TITLE
Modern Maintenance mode page

### ISSUE THREAD

**Issue by Bru-osclass** [mindstellar/Osclass#289]
Can we add maintenance mode page in core ? The first of our install will be use maintenance mode for 2 or 3 days after some modifications and live it. The old one is not modern page just only text info.
1. Can we add some header text (web title And web description )
2. Time countdown with day hour and minutes...
3. Social network..
4. Subscribe alert when site live .

Thank you for work on it

Regard

![3722DF3C-44A1-45CE-A4DE-525B6C8BE19A](https://user-images.githubusercontent.com/71484662/93565981-71fd2100-f9b6-11ea-813f-b0f5a257923d.jpeg)

**Comment by navjottomer** [comment]
In the new release, we have enabled the functionality to add a maintenance template in the theme directory. More this can be done through 3rd party plugins.
