### ISSUE TITLE
Error adding html code in widget

### ISSUE THREAD

**Issue by alex7070m** [mindstellar/Osclass#290]
**Describe the bug**

![26092020-mailruproblem](https://user-images.githubusercontent.com/69157204/94337838-2e2d9b80-fff6-11ea-9953-3464c27b24ad.jpg)

Hello! When I try to add the top rating code https://top.mail.ru/  to the html widget, I get an error:
403
Forbidden
Access to this resource on the server is denied!

If you just add this code to any html page, then there are no problems. I also added similar code via html widget to the wordpress site and there were no problems. I am using php 7.4.

Below is this code:

`
<script type="text/javascript">
var _tmr = window._tmr || (window._tmr = []);
_tmr.push({id: "3170903", type: "pageView", start: (new Date()).getTime()});
(function (d, w, id) {
  if (d.getElementById(id)) return;
  var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;
  ts.src = "https://top-fwz1.mail.ru/js/code.js";
  var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
  if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
})(document, window, "topmailru-code");
</script><noscript><div>
<img src="https://top-fwz1.mail.ru/counter?id=3170903;js=na" style="border:0;position:absolute;left:-9999px;" alt="Top.Mail.Ru" />
</div></noscript>

<a href="https://top.mail.ru/jump?from=3170903">
<img src="https://top-fwz1.mail.ru/counter?id=3170903;t=479;l=1" style="border:0;" height="31" width="88" alt="Top.Mail.Ru" /></a>
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by eurobank** [comment]
This probably comes from your server/hosting, reminds me of mod_security blocks. 

I highly doubt if it is related to Osclass.

**Comment by alex7070m** [comment]
This is the content of the .htaccess file

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

RewriteEngine On

RewriteCond %{HTTPS} off

RewriteCond %{HTTP:X-Forwarded-Proto} !https

RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# BEGIN cPanel-generated php ini directives, do not edit
# Manual editing of this file may result in unexpected behavior.
# To make changes to this file, use the cPanel MultiPHP INI Editor (Home >> Software >> MultiPHP INI Editor)
# For more information, read our documentation (https://go.cpanel.net/EA4ModifyINI)
<IfModule php7_module>
   php_flag display_errors Off
   php_value max_execution_time 30
   php_value max_input_time 60
   php_value max_input_vars 1000
   php_value memory_limit 128M
   php_value post_max_size 20M
   php_value session.gc_maxlifetime 1440
   php_value session.save_path "/var/cpanel/php/sessions/ea-php73"
   php_value upload_max_filesize 50M
   php_flag zlib.output_compression Off
</IfModule>
<IfModule lsapi_module>
   php_flag display_errors Off
   php_value max_execution_time 30
   php_value max_input_time 60
   php_value max_input_vars 1000
   php_value memory_limit 128M
   php_value post_max_size 20M
   php_value session.gc_maxlifetime 1440
   php_value session.save_path "/var/cpanel/php/sessions/ea-php73"
   php_value upload_max_filesize 50M
   php_flag zlib.output_compression Off
</IfModule>
# END cPanel-generated php ini directives, do not edit

# php -- BEGIN cPanel-generated handler, do not edit
# Set the вЂњea-php74вЂќ package as the default вЂњPHPвЂќ programming language.
<IfModule mime_module>
  AddHandler application/x-httpd-ea-php74 .php .php7 .phtml
</IfModule>
# php -- END cPanel-generated handler, do not edit 



I have a wordpress site running on the same hosting and a similar code is inserted without problems via the html widget

**Comment by navjottomer** [comment]
Popular hosting providers do add WordPress specific exceptions in mod_security. You need to talk with your hosting provider to add an exception to your osclass installation in this situation.

**Comment by alex7070m** [comment]
It is clear, but at the same time the code from the site rating liveinternet.ru is installed on the site without any problems:

https://999-ru.com
