### ISSUE TITLE
Beta 5, Location Stats

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#291]
Osclass 5 beta. Location Stats rebuild seems not working. A big pause and nothing.

PHP 7.3

**Comment by navjottomer** [comment]
Any error log, browser console error? It is working fine at my installation.

**Comment by eurobank** [comment]
No errors anywhere. Just a big pause .... and i only have two small countries in the staging site. Then it stops.

**Comment by navjottomer** [comment]
#293
