### ISSUE TITLE
Question: How to TEST beta5? Theme?

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#293]
It seems than Bender ( 3.2.3) doesnt' work right with beta5, OsclassWizards also not at all.

So the question is: HOW to test Osclass beta5? We can't.

Issues: The new ads do not appear. They do not save. No errors in debug.

**Comment by eurobank** [comment]
Not sure if this is a theme issue, since the ads do not also appear in admin listing dashboard.

**Comment by eurobank** [comment]
Strange things happen. A user can register, can post an ad without any errors. BUT his ads do not appear in Listings in admin Dashboard BUT in user profile is shows the correct number. BUT clicking in his profile (admin / users) you get nothing.

**Comment by eurobank** [comment]
This is more an early Alpha than a beta release. Not a negatibe comment. just what i see after spending a few hours playing with beta.

**Comment by navjottomer** [comment]
I checked again and I can post ads with images on bender theme. 
I didn't get any PHP Notice in error_log. Ads are showing in properly both in Admin Dashboard and User Dashboard.
So can you be more specific about the issue and share some useful info so we can really fix it and understand why this is happening at your side and note mine.

A best way to report a bug is to share some more info:
 PHP version:
Fresh Install:
Theme activated:
Language:
Plugins activated:
Error log when this happened.

**Comment by eurobank** [comment]
1. PHP 7.3

2. Database already from 3.9, the rest is from Beta5.

3. Theme Bender 

4. No plugins

5. No errors anywhere.

**Comment by eurobank** [comment]
There are some notices, but maybe they are not related.

[30-Sep-2020 18:23:43 Europe/Madrid] PHP Notice:  Undefined index: fk_i_category_id in /home/oc-includes/osclass/helpers/hDefines.php on line 581
[30-Sep-2020 18:23:43 Europe/Madrid] PHP Notice:  Undefined index: pk_i_id in /home/oc-includes/osclass/helpers/hDefines.php on line 591
[30-Sep-2020 18:23:43 Europe/Madrid] PHP Notice:  Undefined index: s_city in /home/oc-includes/osclass/helpers/hDefines.php on line 592
[30-Sep-2020 18:23:43 Europe/Madrid] PHP Notice:  Undefined index: s_title in /home/oc-includes/osclass/helpers/hDefines.php on line 598

**Comment by eurobank** [comment]
I did a totally fresh install (db and setup) and now listings are saved and appear everywhere. So probably it was because of update from 3.9?

BUT the locations stats not working problem remain.

**Comment by navjottomer** [comment]
Any log while updating location stats?

**Comment by eurobank** [comment]
@navjottomer Nothing. What seems to happen is that if you insist and press calcuatate 2 or 3 times, it seems to work. Still it takes a very long time and seems like a freeze.

**Comment by eurobank** [comment]
Created a NEW Osclass 3.9. 

Posted 2 ads.

Updated to 5beta

Posted 1 ad. No ad was posted anywhere. 

So the issue is real, when updating from pre5 to 5.

This is as far as i can help.

**Comment by eurobank** [comment]
Maybe this 

https://github.com/mindstellar/Osclass/issues/296

is related to the problem?

**Comment by dftd** [comment]
@eurobank Osclasswizards works fine here, I can post ads without problem.

**Comment by eurobank** [comment]
Not related to themes. Doesn't work for me if i UPDATE. Works right on clean install.
