### ISSUE TITLE
There are bugs with new JS library.

### ISSUE THREAD

**Issue by safeacid** [mindstellar/Osclass#296]
After fresh installation there are errors in js.
You can check console.
<img width="1440" alt="Screenshot-2020-10-04-at-12-04-28" src="https://user-images.githubusercontent.com/29160739/95359914-58733900-08d3-11eb-9219-62d63c4e116c.png">

**Comment by eurobank** [comment]
Also in Home Page with Bender:

c-includes/assets/js/fineuploader/fineuploader.css was not loaded because its MIME type, “text/html”, is not “text/css”.

**Comment by eurobank** [comment]
And in Dashboard:
    jQuery 2
        <anonymous>
        <anonymous>
jquery.fancybox.pack.js:2:297

Uncaught TypeError: e.browser is undefined
    jQuery 2
        <anonymous>
        <anonymous>

**Comment by dftd** [comment]
@navjottomer Bender needs some updating for 5.0, should I work on that and release it along with Osclass 5?

**Comment by dftd** [comment]
@eurobank @safeacid Which Bender version is that? I did a clean 5.0 install with the bundled Bender theme and I don't see any errors at all.

**Comment by eurobank** [comment]
This is a CLEAN install, so i guess it is the default Bender theme. I changed nothing at all. 

Just REdid a clean installation, for my peace of mind, and again i get those errors i posted above.

**Comment by eurobank** [comment]
Here is the complete list of errors in HOME page:

1. Uncaught TypeError: Cannot read property 'msie' of undefined
    at jquery.fancybox.pack.js:2
    at jquery.fancybox.pack.js:31


2. Query.Deferred exception: $(...).fancybox is not a function TypeError: $(...).fancybox is not a function
    at HTMLDocument.<anonymous> (https://aaaaa/oc-includes/gui/js/global.js:195:25)
    at e (https://aaaa/oc-includes/assets/js/jquery/jquery.min.js:2:30005)
    at t (https://aaaa/oc-includes/assets/js/jquery/jquery.min.js:2:30307) undefined

3. Uncaught TypeError: $(...).fancybox is not a function
    at HTMLDocument.<anonymous> (global.js:195)
    at e (jquery.min.js:2)


Also only on Firefox i get:

The stylesheet https://aaaa/oc-includes/assets/js/fineuploader/fineuploader.css was not loaded because its MIME type, “text/html”, is not “text/css”.

**Comment by eurobank** [comment]
@dftd You got me thinking, and i see bender directory exists but empty. Is that normal?

**Comment by eurobank** [comment]
This is probably also related, so i attach it here. 

![Screenshot(1)](https://user-images.githubusercontent.com/4467158/96094835-83aee700-0ed6-11eb-9cb4-c3d3cf123ca6.png)

**Comment by eurobank** [comment]
@safeacid All issues are gone if you update Bender with:

https://github.com/mindstellar/theme-bender

Bender 3.2.2

Why isn't that included in the 5 beta files?

**Comment by dftd** [comment]
@eurobank "I see bender directory exists but empty. Is that normal?"

Your oc-content/themes/bender is empty? In that case, it's loading the default, probably outdated version from gui folder.

**Comment by eurobank** [comment]
@dftd Then include some working Bender version in the beta archive pls. Otherwise people will encounter the same issues.

**Comment by dftd** [comment]
@eurobank You got me confused because I have bender theme on my install. I downloaded the release .zip now and I see the theme there.
Maybe it's an old version.

@navjottomer You know more regarding this.

**Comment by eurobank** [comment]
@dftd What zip? The release 5 zip has an empty Bender folder. 

![2020-10-15 12_26_37-Window](https://user-images.githubusercontent.com/4467158/96104726-d9d55780-0ee1-11eb-9ab2-9cf6aa432ed3.png)

**Comment by dftd** [comment]
@eurobank True. My bad. Got confused through all this.

@navjottomer Merge my Bender PR's and then include Bender in the 5.0.0 beta so people can test properly.
Or update the gui folder Bender with the new one.

**Comment by eurobank** [comment]
@dftd This is not a beta release, i'm sorry. We are wasting time testing this. This is alpha something.

PLEASE be more consistent to what you release and do not let weeks and months pass-by without actions.

Otherwise nobody will follow. Please do not take this as a negative comment, you DO know i mean always well.

**Comment by navjottomer** [comment]
I am sorry, I am not here to explain to everyone how git works. 
To clone git submodules you'll have to clone it recursively which is clearly mentioned on the readme file. GUI theme is not updated because I planning to remove it as it's an outdated version of included Bender theme.
