### ISSUE TITLE
HTTP response status code

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#297]
Osclass 3.9, PHP 7.3, no plugins, ALL themes

I see a lot of http error 400 for ad pages that do not exist anymore. Those should return 404 but they do not.

Error 400 means Bad Request but i can't find why. Manually pointing to those urls show "Sorry But I Can't Find The Page You're Looking For" but return http 400 in the header.

Any ideas?

**Comment by dftd** [comment]
https://github.com/mindstellar/Osclass/blob/b22d2288991aa14e92a5774a3187cccfe6a50bdc/oc-includes/osclass/controller/item.php#L601

https://github.com/mindstellar/Osclass/blob/b22d2288991aa14e92a5774a3187cccfe6a50bdc/oc-includes/osclass/controller/item.php#L610

@eurobank According to this code, 400 should show only when items are inactive or blocked, is that the case or they're deleted?

**Comment by eurobank** [comment]
thanks @dftd for the tip. 

Actually those are indeed inactive or unapproved items. Not deleted.

So the question is why they appear in search engines?
