### ISSUE TITLE
Osclass 5beta and Bender 3.2.2

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#306]
Some cookies are misusing the recommended “SameSite“ attribute 2

Cookie “qqCookieTest:91191.46876971614” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite jquery.fineuploader.min.js:16:7331

Cookie “qqCookieTest:91191.46876971614” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite jquery.fineuploader.min.js:16:7331

**Comment by dftd** [comment]
Fineuploader is an outdated mess. I'm working on a new image upload solution.
