### ISSUE TITLE
Osclass 5 beta release phpmailer crash

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#307]
Item posting of unregister users (nothing wrong with "to:" email address, not empty or anything, a valid email address")  :  

[15-Oct-2020 13:48:09 Europe/Madrid] PHP Fatal error:  Uncaught PHPMailer\PHPMailer\Exception: Invalid address:  (to):  in /home/oc-includes/vendor/phpmailer/phpmailer/src/PHPMailer.php:1079

Stack trace:
0 /home/oc-includes/vendor/phpmailer/phpmailer/src/PHPMailer.php(1001): PHPMailer\PHPMailer\PHPMailer->addOrEnqueueAnAddress('to', '', '')

1 /home/oc-includes/osclass/utils.php(338): PHPMailer\PHPMailer\PHPMailer->addAddress('', NULL)

2 /home/oc-includes/osclass/emails.php(1572): osc_sendMail(Array)

3 /home/oc-includes/osclass/classes/Plugins.php(403): fn_email_item_validation_non_register_user(Array)

4 /home/oc-includes/osclass/helpers/hPlugins.php(37): Plugins::runHook('hook_email_item...', Array)

5 /home/oc-includes/osclass/classes/actions/ItemActions.php(595): osc_run_hook('hook_email_item...', Array)

6 /home/oc-incl in /home/oc-includes/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 1079

**Comment by dftd** [comment]
@eurobank How can I replicate the problem?
Posting an ad while logged out doesn't seem to cause problems, even when "Users must validate their listings" is on.

**Comment by eurobank** [comment]
I just tried to post an ad, while a VISITOR. Nothing else.

You can always contact me privately if you want.

**Comment by dftd** [comment]
@navjottomer I did some debugging on @eurobank's site and found the problem.
He upgraded from 3.9 to 5.0 by replacing the files, but the whole item-post situation broke due to a missing database field (s_contact_phone).

Not sure if there's an auto DB update system already, but we need a check like `if(version < 5.0) { fixDatabase(); }`. Could you take a look at that?

**Comment by dftd** [comment]
@eurobank Just checked on this, as per the official documentation for upgrading (https://docs.mindstellar.com/osclass-docs/beginners/updating-osclass) which we both ignored, you are supposed to upgrade your database by heading to http://www.example.com/oc-admin/index.php?page=upgrade&action=upgrade-funcs.

I made a PR that will show a "Database update is available" notification in the admin header.

**Comment by eurobank** [comment]
Well that is an unusual way to upgrade without even a notice. Different from 3.9 or Wordpress .... Anyways.

**Comment by navjottomer** [comment]
> Well that is an unusual way to upgrade without even a notice. Different from 3.9 or Wordpress .... Anyways.

BTW those docs are heavily borrowed from the previous Osclass, It's not a new thing It is added as a safe point if in any case auto database upgrade doesn't work (due to some error, which have to be reported so we can fix those issues).

**Comment by eurobank** [comment]
Well, i always updated osclass via ftp, never auto. 3.9 (yours) included. Never had an issue.

**Comment by navjottomer** [comment]
I alone can't test everything all alone it's beta what did you expect? Even full release can have unseen bugs.

**Comment by eurobank** [comment]
whatever ... good luck.

**Comment by eurobank** [comment]
Even your suggestion and @dftd Doesn't seems to work right.


Upgrade
Upgrading your Osclass installation (this could take a while): "

and sits in there. Not sure what happens, upgraded or not.

So pls next time you get angry, find somebody else to vent off. I only try to help, since nobody cares anymore.

**Comment by dftd** [comment]
@eurobank It updates the DB I think but no message shows. I made a PR few days ago to fix that.

**Comment by eurobank** [comment]
@dftd Ok, still there is NO way to know what for the webmasters. 

**Also if you try to UPGRADE again with the same url, you get the same result.**

While you should get that your DB IS UPGRADED already.

All in all, most users will use the upgrade. A few will install as new. And if they can't, you know the rest ....

I know you did a fix and thank you. I will check it out when included and finilized.
