### ISSUE TITLE
Import items from another osclass

### ISSUE THREAD

**Issue by AnonymousWebHacker** [mindstellar/Osclass#309]
Situation:
I have an osclass on my localhost, and my friend has another one on his localhost.
I have different items than he has. and he has items that I don't have.

There is the possibility of some bot, or some way that example, I can copy the article for sale, and photo of the article, from your osclass?
[I do not have access to your database]
I just want to see in my osclass, the articles that he has in his osclass, it is not necessary the same users or anything, only the articles

It is time for you to think about the theory of decentralization, just like matrix or peertube .
I hope this helps you create a federated osclass subnet, or else create a bot or something, that does this job

**Comment by dftd** [comment]
@AnonymousWebHacker You can use an XML importer/exporter plugin.

**Comment by AnonymousWebHacker** [comment]
> 
> 
> @AnonymousWebHacker You can use an XML importer/exporter plugin.

Can you tell me an example?

**Comment by AnonymousWebHacker** [comment]
@dftd This Oscalss repo, is dead too?

**Comment by navjottomer** [comment]
This isn't hard to find. Didn't tested but should work
https://github.com/mindstellar/Osclass-Extras/blob/master/plugins/20140514101129_53_plugins_importer_0.6.0.zip

**Comment by AnonymousWebHacker** [comment]
wow, tnks @navjottomer , let me test
