### ISSUE TITLE
Oscass config email nginx

### ISSUE THREAD

**Issue by AnonymousWebHacker** [mindstellar/Osclass#313]
**Describe the bug**
I use nginx as a web server, and not apache2. But I have a problem.
Everything is perfect, except the mail.

**To Reproduce**
My mail server uses tls or ssl.
Why is this apache module necessary?
How can I solve that?

**Screenshots**
![mail](https://user-images.githubusercontent.com/43164089/99357892-00a1f780-28ad-11eb-9864-08d0075a63b3.png)

**Comment by eurobank** [comment]
It is not necessary. Disable it and ignore it. It was always like that.

**Comment by AnonymousWebHacker** [comment]
> It is not necessary. Ignore it. It was always like that.

The other sites that I have hosted, they send without problems, but osclass does not send anything, it says configuration fine, but it never sends the emails.
Where can I see the log of the mail delivery?

**Comment by AnonymousWebHacker** [comment]
> Ask your hosting provide for all that.
> 
> Osclass sends email very well, not an issue ever. It is usually a hosting/mail server issue.
> 
> Here is what i use in more than 20 sites.


Thanks, the configuration is fine, I am my own hostin provider. And fix the problem already.
I thought, it was problems for using nginx and the site asking me for an apache module

It was well configured, but I already had registered users with other (fake) domains, so a queue was made to send emails to addresses that did not exist.

**Comment by siberalem61** [comment]
# # @AnonymousWebHacker 
How did you fix that on nginx ?
