### ISSUE TITLE
Latest 5 beta - Old link to osclass.org in BUILD-IN Bender

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#319]
Osclass 5 beta CLEAN install, with nothing else.

It seems some relic is found. A link to osclass . org !

![Screenshot](https://user-images.githubusercontent.com/4467158/122240309-59308600-ceca-11eb-8a00-ad182c1a22aa.png)

**Comment by eurobank** [comment]
And an other one in Theme settings

![Screenshot](https://user-images.githubusercontent.com/4467158/122240690-a44a9900-ceca-11eb-8d93-74f382d5acd5.png)

**Comment by navjottomer** [comment]
Those are the bender theme issue, not related to Osclass. It will be fixed there.
