### ISSUE TITLE
Osclass not marking unknown visitors ads Invalid but sending validation emails.

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#320]
Everyone can post in my test site. Visitors also.

While i have NOT enabled that visitors must validate their ads, they get an email to validate it.

But the ad IS posted. Probably a bug of a not necessary email.

**Comment by navjottomer** [comment]
I checked it and the Email validation function is working fine.
The default behaviour of Osclass is to send validation email if they're not registered, another way to fight spam.
Setting in Admin Dashboard is for asking validation from the registered user. That's what I checked and everything is fine.

Still, if you want to disable it add this line of code in your theme's functions.php
```php
osc_remove_hook('hook_email_item_validation_non_register_user', 'fn_email_item_validation_non_register_user');
```
This fill removes default behaviour.

**Comment by eurobank** [comment]
How can Osclass PUBLISH an ad but asks to be validated also? Validate what? since it is already published.

It doesn't work right but if you say it is ok ... i can't do anything further.

**Comment by navjottomer** [comment]
> How can Osclass PUBLISH an ad but asks to be validated also? Validate what? since it is already published.
> 
> It doesn't work right but if you say it is ok ... i can't do anything further.

The issue is osclass is not marking ads invalid, the mail thing is right.

**Comment by eurobank** [comment]
The issue is that you DISABLE validation for **anyone** and it does't work that way. If you disable validation, the ad is posted rightaway and NO email is needed.

**Comment by navjottomer** [comment]
> The issue is that you DISABLE validation for **anyone** and it does't work that way. If you disable validation, the ad is posted rightaway and NO email is needed.

Where is the setting to disable validation for everyone? It is for users.

**Comment by eurobank** [comment]
There is an option for LOGGED IN USERS not to validate their posts, **so it is NOT for everyone as you say**.

**Comment by navjottomer** [comment]
> There is an option for LOGGED IN USERS not to validate their posts, **so it is NOT for everyone as you say**.

Indeed there is an option, I didn't see it because my option was disabled. Fixed

**Comment by navjottomer** [comment]
BTW thanks, this could have been unnoticed for a long.

**Comment by eurobank** [comment]
No problem, always glad to help and test everything. Since nobody (except you) does test ....
