### ISSUE TITLE
DB upgrade errors from 5 beta to beta.9

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#326]
Not sure what those are:

Upgrade
Upgrading your Osclass installation (this could take a while):
Error: Osclass » Has some errors
We've encountered some problems while updating the database structure.
The following queries failed:
ALTER TABLE oc_t_admin CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_alerts CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_ban_rule CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_category CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_category_stats CHANGE COLUMN fk_i_category_id fk_i_category_id INT UNSIGNED NOT NULL PRIMARY KEY
ALTER TABLE oc_t_city CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_city_area CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL PRIMARY KEY
ALTER TABLE oc_t_city_stats CHANGE COLUMN fk_i_city_id fk_i_city_id INT UNSIGNED NOT NULL PRIMARY KEY
ALTER TABLE oc_t_item CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_item_comment CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_item_location CHANGE COLUMN fk_i_item_id fk_i_item_id INT UNSIGNED NOT NULL PRIMARY KEY
ALTER TABLE oc_t_item_resource CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_meta_fields CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_pages CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_region CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_region_stats CHANGE COLUMN fk_i_region_id fk_i_region_id INT UNSIGNED NOT NULL PRIMARY KEY
ALTER TABLE oc_t_user CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
ALTER TABLE oc_t_user_email_tmp CHANGE COLUMN fk_i_user_id fk_i_user_id INT UNSIGNED NOT NULL PRIMARY KEY
ALTER TABLE oc_t_widget CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
These errors could be false-positive errors. If you're sure that is the case, you can 

"status":true,"message":"Osclass DB Upgraded Successfully"}

and stuck in the above page ({"status":true,"message":"Osclass DB Upgraded Successfully").

Any ideas what all these are? In debug log some "error queries" are logged also, probably same as above.

**Comment by navjottomer** [comment]
> 
> Upgrade
> Upgrading your Osclass installation (this could take a while):
> Error: Osclass » Has some errors
> We've encountered some problems while updating the database structure.
> The following queries failed:
> ALTER TABLE oc_t_admin CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_alerts CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_ban_rule CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_category CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_category_stats CHANGE COLUMN fk_i_category_id fk_i_category_id INT UNSIGNED NOT NULL PRIMARY KEY
> ALTER TABLE oc_t_city CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_city_area CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL PRIMARY KEY
> ALTER TABLE oc_t_city_stats CHANGE COLUMN fk_i_city_id fk_i_city_id INT UNSIGNED NOT NULL PRIMARY KEY
> ALTER TABLE oc_t_item CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_item_comment CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_item_location CHANGE COLUMN fk_i_item_id fk_i_item_id INT UNSIGNED NOT NULL PRIMARY KEY
> ALTER TABLE oc_t_item_resource CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_meta_fields CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_pages CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_region CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_region_stats CHANGE COLUMN fk_i_region_id fk_i_region_id INT UNSIGNED NOT NULL PRIMARY KEY
> ALTER TABLE oc_t_user CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> ALTER TABLE oc_t_user_email_tmp CHANGE COLUMN fk_i_user_id fk_i_user_id INT UNSIGNED NOT NULL PRIMARY KEY
> ALTER TABLE oc_t_widget CHANGE COLUMN pk_i_id pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> These errors could be false-positive errors. If you're sure that is the case, you can
> 
> "status":true,"message":"Osclass DB Upgraded Successfully"}
> 
> and stuck in the above page ({"status":true,"message":"Osclass DB Upgraded Successfully").
> 
You're are getting an error query log and JSON status booth at the same page?
MySQL version?
MySQL 8 INT type column display width is deprecated, it causes these error on upgrading. These are false-positive errors, but they shouldn't throw.
Share a screenshot of the error if you can, looking into it BTW.

**Comment by eurobank** [comment]
I use 10.3.28-MariaDB-log-cll-lve.

**Comment by eurobank** [comment]
![Screenshot(1)](https://user-images.githubusercontent.com/4467158/122895514-d9367000-d350-11eb-8624-badfb090bab5.png)

![Screenshot (4)](https://user-images.githubusercontent.com/4467158/122895525-dcc9f700-d350-11eb-83ad-5d89cb087116.png)

**Comment by navjottomer** [comment]
See #326 and let me know if it does fix it.

**Comment by eurobank** [comment]
With your fix, the upgrade finishes ok, no errors BUT the debug log is FULL of warnings :

PHP Warning:  strtolower() expects parameter 1 to be string, array given in /home/oc-includes/osclass/classes/database/DBCommandClass.php on line 1731

or 

[22-Jun-2021 11:16:57 Europe/Madrid]  --- pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY

or 

[22-Jun-2021 11:16:57 Europe/Madrid]  --- b_moderator TINYINT(1) NOT NULL DEFAULT 0

and similar.

**Comment by navjottomer** [comment]
Those logs are enabled to keep logs of data queries run while upgrading or installing. Those are harmless messages.

Except this but nothing fatal.
`
PHP Warning: strtolower() expects parameter 1 to be string, array given in /home/oc-includes/osclass/classes/database/DBCommandClass.php on line 1731
`

BTW  after occurring those errors "continue installation" link should redirect to the upgrade the page with the success banner. It shouldn't output JSON. will fix that.

**Comment by navjottomer** [comment]
New fixes, I hope finally.

**Comment by eurobank** [comment]
No errors or warnings this time, still after the upgrade, see the final page:

![Screenshot](https://user-images.githubusercontent.com/4467158/122917894-32a99980-d367-11eb-8f39-856839ce2a37.png)

**Comment by navjottomer** [comment]
> No errors or warnings this time, still after the upgrade, see the final page:
> 
>
This is alright, marking this issue as closed.
