### ISSUE TITLE
Osclass 5 b.9 New Installations Locations issue with countries having space in name

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#329]
New Install, clean DB. Location USA i selected didn't install, with an error at the end "The selected location could not been installed". 

before the error see what shows:

![2021-06-22 19_27_39-Osclass Installation — Mozilla Firefox](https://user-images.githubusercontent.com/4467158/122965602-0c005880-d391-11eb-9755-37b49d1ee1d5.png)

btw: the "been installed" should be "be installed"

**Comment by eurobank** [comment]
And then trying to Import a location in admin dashboard, the selector is empty. I can't.

![2021-06-22 19_44_38-Locations » Mozilla Firefox](https://user-images.githubusercontent.com/4467158/122966883-87aed500-d392-11eb-9e7d-62be385838f6.png)

**Comment by eurobank** [comment]
[22-Jun-2021 18:48:38 Europe/Madrid] PHP Fatal error:  Uncaught Error: Call to undefined method View::listNames() in /home/oc-admin/themes/modern/settings/locations.php:540
Stack trace:
#0 /home/oc-includes/osclass/helpers/hDefines.php(215): require()
#1 /home/oc-includes/osclass/classes/controller/base/AdminSecBaseModel.php(112): osc_current_admin_theme_path('settings/locati...')
#2 /home/oc-includes/osclass/classes/controller/admin/settings/CAdminSettingsLocations.php(552): AdminSecBaseModel->doView('settings/locati...')
#3 /home/oc-includes/osclass/classes/controller/admin/CAdminSettings.php(96): CAdminSettingsLocations->doModel()
#4 /home/oc-admin/index.php(77): CAdminSettings->doModel()
#5 {main}
  thrown in /home/oc-admin/themes/modern/settings/locations.php on line 540

**Comment by navjottomer** [comment]
Fixed

**Comment by eurobank** [comment]
Not fixed in 5.0.2 i just installed and tested.

**Comment by navjottomer** [comment]
Not happening in develop branch though.
