### ISSUE TITLE
More Secure Admin Password for new Installations

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#333]
I see that the auto-generated admin password is so and so in terms of security.

Could that be improved, adding some symbol also?

**Comment by navjottomer** [comment]
Currently, this method is responsible for generating password and secrets and get used for different purposes.  
```php 
function osc_genRandomPassword($length = 8)
{
    $dict = array_merge(range('a', 'z'), range('0', '9'), range('A', 'Z'));
    shuffle($dict);

    $pass = '';
    for ($i = 0; $i < $length; $i++) {
        $pass .= $dict[mt_rand(0, count($dict) - 1)];
    }

    return $pass;
}
```
Changing this can lead to random behaviour, I think we can skip it for the current release. Had to work on languages too, like locations they too need an update. Will push a new beta of this build and if everything is okay then push for RC.
