### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by maddrid** [mindstellar/Osclass#344]
**Describe the bug**
on install 
PHP Fatal error:  Uncaught Error: Call to undefined function osc_is_admin_user_logged_in() in J:\xampp\htdocs\osclass5\oc-includes\osclass\classes\database\DBConnectionClass.php:417

**Comment by navjottomer** [comment]
Call to this function only happen when OC_DEBUG is set to true, This is not the case while installing.
How did you get this error? Steps to reproduce would be better.

**Comment by navjottomer** [comment]
Please open it, if you have some more info.
