### ISSUE TITLE
Repo shows JS as main language

### ISSUE THREAD

**Issue by dftd** [mindstellar/Osclass#347]
A totally random thing, but it's an easy fix so whatever.

Create `.gitattributes` file in root, and in it put something like this to ignore assets folders when picking main repo language.

```
/oc-includes/assets/* linguist-vendored
```

**Comment by navjottomer** [comment]
It will break our build script as git-archive ignore files in added in .gitattributes.
It is showing javascript as the main language because of tiny_mce, some plugins need to be removed as they are not needed. 
Will fix that before release.

**Comment by navjottomer** [comment]
Fixed now.
