### ISSUE TITLE
Unreliable keyword search by relevance

### ISSUE THREAD

**Issue by Tangol** [mindstellar/Osclass#348]
As per this report here https://github.com/mindstellar/Osclass/issues/260 , the keyword search by relevance wasn't fixed.

If you edit and remove the keyword from the listing title and leave it only in the description, it still appears as the most relevant search.

It's like the relevance script takes a snapshot of the original listings and doesn't update anymore, if the listing gets edited...
Also, it seems that after you've made a search by relevance, if other more relevant listings get added (after), they will not count in a new relevance search.
Almost like the first search gets cached somehow and if something new appears, it still returns the first sort. 

I don't know if it makes sense, as I can't explain it better. 

- Tested on Osclass 5.0.0 with `oc_t_item_description` on both MyISAM and InnoDB - MySQL 8.0.21

**Comment by navjottomer** [comment]
Okay, I'll check, maybe it needs some fine-tuning to acceptable liking.

**Comment by navjottomer** [comment]
Finally tested it again, it has some issues but not as you have described.
I have made some changes in develop branch see 06c9c13dfc1ab2460de79b61b7bfe37df5251fe5

Let me know if the issue still persists on develop branch.
