### ISSUE TITLE
Fatal error when you try to `install` on PHP 8

### ISSUE THREAD

**Issue by adrianolmedo** [mindstellar/Osclass#349]
**Describe the bug**
Trying to install Osclass 5.0.0 with PHP 8 I get a `Fatal error`.

**To Reproduce**
1. Run Docker environment with PHP 8+Apache+MySQL 8
2. Click on http://172.17.0.1:5000/
4. See error:

```
Fatal error: Uncaught Error: Undefined constant "WEB_PATH" in /var/www/html/oc-includes/osclass/helpers/hDefines.php:48 Stack trace: #0 /var/www/html/oc-includes/osclass/classes/utility/FileSystem.php(640): osc_base_url() #1 /var/www/html/oc-includes/osclass/utils.php(872): mindstellar\utility\FileSystem->getContents('https://raw.git...', NULL, false) #2 /var/www/html/oc-includes/osclass/install.php(66): osc_file_get_contents('https://raw.git...') #3 {main} thrown in /var/www/html/oc-includes/osclass/helpers/hDefines.php on line 48
```

![osclass-v5 0 0-fatal-error](https://user-images.githubusercontent.com/10823779/128807872-534509a0-09a0-4ca0-b142-cb7053018484.png)

**Expected behavior**
Get installation page.

**Comment by adrianolmedo** [comment]
Well, this bug could be fixed removing `osc_` from [oc-includes/osclass/install.php#L66](https://github.com/mindstellar/Osclass/blob/cf278c55d7d0964e25655334729c522bf5fbf2b4/oc-includes/osclass/install.php#L66):

```php
$jsonLocales = osc_file_get_contents(osc_get_languages_json_url());`
```

To:

```php
$jsonLocales = file_get_contents(osc_get_languages_json_url());`
```

**Comment by navjottomer** [comment]
I have identified the issue, a fix is ready will upload it asap. The issue is that the function using a constant which is not has been defined. 'file_get_contents' can cause other error as some host disable 'allow_url_fopen'.

**Comment by navjottomer** [comment]
Please test the latest release, I have successfully installed it on PHP 8.0 using docker.

**Comment by adrianolmedo** [comment]
It works well! good job
