### ISSUE TITLE
New Backend User Interface

### ISSUE THREAD

**Issue by navjottomer** [mindstellar/Osclass#353]
A new backend interface is in development. Need some testing and suggestions from the community and features will be finalized then.

**Comment by navjottomer** [comment]
@dftd can you test?

**Comment by dftd** [comment]
I didn't notice any breaking issues with the theme, but here's some constructive criticism regarding overall UI/UX.

Design is inconsistent in some places, stuff like input boxes and font size.
I'd replace some buttons with icons (like search filter) with buttons that have actual text so it's more clear.
In my opinion, "Advanced options" when adding a custom field should be visible immediately.
Some parts are not really responsive. `min-width: 450px;` property of `#content-page` causes most of the problems with that.
Bit unrelated, but came to my mind when testing... We should finally add reordering of custom fields.

I'll be off next week but when I'll be back I can work on some of those issues, if you want.

**Comment by navjottomer** [comment]
Thanks for the quick review, It's not finalized yet. 
It was too hard to maintain compatibility, as some parts of the theme are totally different from others. 3-4 types of CSS properties were created for the same type of inputs. And I assume that some old plugin would have used those properties too. 
It's was time-consuming to delete some and to retain some aspects of the old structure. 
It would have been easier to just make CSS changes, but a framework was needed to be added to be worked upon as time progressed. The whole theme was a cluttering mess of jquery and CSS by today's standards (It is still in some). 
Few goals I had in mind before working on it.

- Make this theme compatible with the new Bootstrap5 framework without making any major breaking changes, so old plugins/themes can live another day.
- Reduce our reliance on jquery and port as much as possible to pure Javascript. (Which I guess time-consuming) .
- Provide standard classes which plugins and theme developers can use to generate backend views, actions. FormInput class is ready to take some responsibility for it. We just need a wrapper class to bind them all and provide a single entry point to access all these new features for developers.
- After all this only, I can start with a free theme/plugin store UI

After working on the modern theme one thing I understood is that it's too time consuming to do all that in one go, and it certainly breaks few things here and there if I rushed and will be hard to find. Because either I can write code or test.
I think it's better to make it a gradual process and merge all work and let other people test, so I can focus on things necessary.

All help is appreciated. I want the next major release to be more feature-rich with better backend UI and few hands are needed in that process.

**Comment by navjottomer** [comment]
Made some changes.
