### ISSUE TITLE
Code modifier

### ISSUE THREAD

**Issue by never-failing** [mindstellar/Osclass#356]
Modifiers are modules of sorts that allow you to make changes to functionality or appearance without affecting the original files. This ensures that the engine files remain unchanged, but at the same time you can change or add functionality. For example, there is such a thing in opencart or dle. Maybe I didn't make it clear, I'll try to give an example:
[1.txt](https://github.com/mindstellar/Osclass/files/7027468/1.txt)

**Comment by dftd** [comment]
There is a such plugin, check it out. https://github.com/codexilab/osclass-vqmod

**Comment by never-failing** [comment]
> 
> 
> Есть такой плагин, посмотрите. [https://github.com/codexilab/osclass-vqmod ](https://github.com/codexilab/osclass-vqmod)
Спасибо огромное, задавал
