### ISSUE TITLE
XSS in URL custom fields

### ISSUE THREAD

**Issue by dftd** [mindstellar/Osclass#357]
URL custom fields are very easily exposed to XSS attacks.

I can set a value as simple as `http://" onclick="alert(1)"` and the Javascript will be executed on click on item details page.

![image](https://user-images.githubusercontent.com/53878055/131245637-d53cef14-53ea-492b-850b-22751897ad77.png)
![image](https://user-images.githubusercontent.com/53878055/131245642-a05e5ffc-47e2-49d3-b02b-b7ac89bfeec7.png)
![image](https://user-images.githubusercontent.com/53878055/131245647-0637ba2e-5add-436f-abc5-c63da9bc9b57.png)

**Comment by navjottomer** [comment]
A fix is ready will upload it soon, btw issues like these shouldn't be made public before fix

**Comment by dftd** [comment]
> A fix is ready will upload it soon, btw issues like these shouldn't be made public before fix

Thanks, I'll close it now so it's atleast a bit harder to find. 😅 

Wondering how no one spotted this issue all this years. 👀

**Comment by navjottomer** [comment]
At least you found it. sanitizer class has some work now.
