### ISSUE TITLE
Upgrading to 5.0.2

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#362]
I have upgraded to 5.0.2 in a staging site. I used Bender theme from here.

Everything seems to be justified to the right or something like that. Or better like reading from right to left.

 Any ideas why?

![Screenshot](https://user-images.githubusercontent.com/4467158/132134872-22ee30b5-2837-4f18-a365-4427e53060e0.png)

**Comment by navjottomer** [comment]
Check your locale, or theme bender rtl setting.

**Comment by eurobank** [comment]
right. not sure why rtl was enabled, anyways ....

**Comment by navjottomer** [comment]
Don't worry let me know if you find anything unusual. I'll open this issue again.
