### ISSUE TITLE
Field validation/trimming issues

### ISSUE THREAD

**Issue by Tangol** [mindstellar/Osclass#363]
Please note that HTML Purifier v4.12.0 has a bug that trims the **0**'s from numbers, if 0 is the first number in the string.
For example, if you have a phone number like `0123456789`, it will register only `123456789`.
https://github.com/ezyang/htmlpurifier/commit/df923d1f1577b6dfa2e5bece50a1b6a5c447cf29

The problem is that from my tests, v4.13.0 doesn't fix the issue. First zeros are still trimmed.

PS: the **+** from the coutry code also gets trimmed. So +91123456789 becomes 91123456789.

Tested on Osclass 5.0.2

**Comment by navjottomer** [comment]
What's your suggestion? We have no control on 3rd party libraries. I can only downgrade or upgrade the version, creating our own patch for 3rd party libraries will make them hard to upgrade and maintain later. Or we just remove the requirement of HTMLPurifier altogether.

**Comment by navjottomer** [comment]
Testing steps?

**Comment by Tangol** [comment]
This guy has it fixed [here](https://osclass-classifieds.com/download), using the latest Html Purifier. I'm still looking at his code but I couldn't find what he did to bypass this.
I think he somehow changed the way the validation for the phone field works, in the Osclass core, not the library.
This one is above my knowledge.

But still, I wouldn't remove the Purifier.

**Comment by Tangol** [comment]
Steps:
- Install fresh Osclass 5.0.2
- Create a user account
- Go to `/user/profile` and add a Phone Number like: **0123456789** or **+91123456789**
- Result: **0** and **+** get trimmed

**Comment by navjottomer** [comment]
I checked my development branch, it didn't have any issue with it after this aaa68c732f0a2c4a50cdc50010d71e979537add3. 
Although I have significantly refactored it already from the base branch. The Library version is still at 4.12

**Comment by navjottomer** [comment]
> 
> But still, I wouldn't remove the Purifier.
I didn't mean to remove it without a proper alternative. It's still a tank for dodging bullets. Relying on it for everything is a performance issue.

**Comment by Tangol** [comment]
https://github.com/mindstellar/Osclass/commit/aaa68c732f0a2c4a50cdc50010d71e979537add3 works perfectly.
@navjottomer you're a saint! Thanks!

**Comment by Tangol** [comment]
I've tested some more, and it seems that the Phone fields (`s_phone_land`, `s_phone_mobile`) don't have any validation.
I mean you can write anything you want in those fields, like: `http://" onclick="alert(1)"`
The phone fields should only allow digits, spaces and a `+` at the beginning of the line.

![phone](https://user-images.githubusercontent.com/3336728/132351909-a436d482-8723-4c22-9b6e-329d1283f80b.png)

**Comment by navjottomer** [comment]
> @navjottomer I've tested some more, and it seems that the Phone fields (`s_phone_land`, `s_phone_mobile`) don't have any validation.
> ![phone](https://user-images.githubusercontent.com/3336728/132351909-a436d482-8723-4c22-9b6e-329d1283f80b.png)

I think now have to refactor UserActions.php

**Comment by Tangol** [comment]
From what I'm seeing, the validation happens in `\oc-includes\osclass\helpers\hValidate.php`
But for some reason, the entire validation there is ignored.

For example the **username** validation:
```
function osc_validate_username($value, $min = 1)
{
    return mb_strlen($value, 'UTF-8') >= $min && preg_match('/^[A-Za-z0-9_]+$/', $value);
}
```
If you change `$min = 1` to `$min = 3`, it will still allow user names with 1 character in them.

**Comment by navjottomer** [comment]
`username` while publishing or while registering new users? In develop?

**Comment by Tangol** [comment]
> `username` while publishing new ad or while registering new users? In develop?

Username here:
![usern](https://user-images.githubusercontent.com/3336728/132359627-d3161078-b0a2-42cb-b6ea-c8c7035ce51a.png)

**Comment by navjottomer** [comment]
I'll try to check as soon as possible, need some rest now.

**Comment by Tangol** [comment]
> I think now have to refactor UserActions.php

You were right.
I got the **phone validation** working with:
```
            if( !osc_validate_phone($input['s_phone_mobile']) ) {
                $flash_error .= _m('The phone is not valid') . PHP_EOL;
                $error[] = 12;
            }
```
In `UserActions.php`

The validation uses the `osc_validate_phone` from `hValidate.php`

**Comment by navjottomer** [comment]
I have created new sanitizer class, it'll be used for sanitation, than above validation method.

**Comment by navjottomer** [comment]
Made some sanitization related changes. Check if they fixed the sanitization issue for you or not. We come to the validation part later.

**Comment by Tangol** [comment]
Please note that https://github.com/mindstellar/Osclass/commit/b16d9641562db1696090645d877fd2ed6feb2f8d breaks the admin login.
I can't login.

![bug](https://user-images.githubusercontent.com/3336728/132567222-af38fea1-27b1-4d4d-8897-ec6fec2cf9c3.png)

**Comment by Tangol** [comment]
Also, while testing some more, this commit https://github.com/mindstellar/Osclass/commit/aaa68c732f0a2c4a50cdc50010d71e979537add3 breaks the listings (editing, deleting), and also the standard `Example Ad` doesn't get created anymore at install.

![bug2](https://user-images.githubusercontent.com/3336728/132571000-1ea9b0b4-df82-455c-b1af-66c552962d1d.png)

**Comment by navjottomer** [comment]
> Please note that [b16d964](https://github.com/mindstellar/Osclass/commit/b16d9641562db1696090645d877fd2ed6feb2f8d) breaks the admin login.
> I can't login.
> 

This was caused by another commit in which I added the new Osclass Error handling class, one its methods bypassing the CSRF shutdown function, it is fixed.




> Also, while testing some more, this commit [aaa68c7](https://github.com/mindstellar/Osclass/commit/aaa68c732f0a2c4a50cdc50010d71e979537add3) breaks the listings (editing, deleting), and also the standard `Example Ad` doesn't get created anymore at install.

Looking into it.

**Comment by navjottomer** [comment]
Checked, it was a DB escaping bug, which I caused while fixing the phone number trimming issue.
