### ISSUE TITLE
5.0.2 - Listing Custom Field issue

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#365]
I have one listing custom field "website" url type, not required.

Trying to post an ad, i get Website not valid, when trying to save the ad. But i put nothing in that field.

**Comment by eurobank** [comment]
Could this be the fix:

https://github.com/mindstellar/Osclass/commit/6b079af2c0923c41e37810182b3bab288889151f

**Comment by navjottomer** [comment]
yes, it is.
