### ISSUE TITLE
Admin Dashboard - Empty Titles

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#366]
In one site i upgraded to 5.0.2, the Listings titles doesn't show as empty.

The only thing i can imagine it is different in this site is the default language that is not english/latin characters. I haven't seen that in an other English site.

![Screenshot](https://user-images.githubusercontent.com/4467158/132301130-b95ac50f-01ae-4dbc-9c88-0d3667a618d5.png)

**Comment by eurobank** [comment]
Also i see those in debug log and probably they are related?

PHP Notice:  Undefined index: s_title in /home/oc-includes/osclass/classes/datatables/ItemsDataTable.php on line 246
PHP Notice:  Undefined index: s_title in /home/oc-includes/osclass/classes/datatables/ItemsDataTable.php on line 247

**Comment by eurobank** [comment]
Also when trying to Edit an ad via the admin dashboard, there are two issues:

The Title field is Empty (saying *Enter title here) AND the description field in TinyMCE is also empty.

I'm adding this comment to this issue because i think it is related.

![Screenshot](https://user-images.githubusercontent.com/4467158/132308003-bfddc7c9-f072-4ca3-ab75-3d40462f9f09.png)

**Comment by eurobank** [comment]
The titles show correct in home pages and other public pages and also in User dashboard. The user CAN view and edit correctly the ad.

So the issues happen only in the Admin Dashboard.

**Comment by navjottomer** [comment]
PHP version?

**Comment by eurobank** [comment]
PHP 7.3.x

**Comment by navjottomer** [comment]
inspect it in browser find for hidden title/description, let me know about your finding.

**Comment by eurobank** [comment]
Categories, locations, user, show correctly in the default language.

**Comment by eurobank** [comment]
I see 

<td class="col-title"> == $0

and then some href

**Comment by eurobank** [comment]
In the empty title IN tinymce, i see "<input id="title[el_GR]" type="text" name="title[el_GR]" value="">"

And in the empty body i see:

<body id="tinymce" class="mce-content-body " data-id="description[el_GR]" spellcheck="false" contenteditable="true"><p><br data-mce-bogus="1"></p></body>

**Comment by navjottomer** [comment]
@eurobank check now.

**Comment by eurobank** [comment]
I'm a little confused, what shall i apply? You reverted? 

Can you guide pls?

Shall i apply only this?

https://github.com/mindstellar/Osclass/commit/ac43224faa1cae20d1227888708d13b965a7f6c8

**Comment by navjottomer** [comment]
Yup

**Comment by eurobank** [comment]
Works just fine now.
