### ISSUE TITLE
Extreme DB usage

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#368]
Litespeed server, Osclass 5.0.2, PHP 7.3.x

4 Osclass installations.

After updating all of them yesterday, i see extreme peaks of DB usage.

See a 7 days stats from Cpanel.

![Screenshot (3)](https://user-images.githubusercontent.com/4467158/132417438-b4f519fe-286b-4f1e-ba66-30582317ee17.png)

**Comment by eurobank** [comment]
This seems to be like a hourly CRON issue. Probably some plugin doesn't work well with Osclass 5. I will debug this.

I will update here after 24 hours or so, please keep this open for 1-2 days, just in case.

**Comment by eurobank** [comment]
Even with most plugins disabled the issue is there. So maybe this comes from Osclass 5?

I will disable the build in cron for now and see  if this is the cause. 

![Screenshot](https://user-images.githubusercontent.com/4467158/132479126-488931a9-4dff-45f4-89fc-a00dd0dc95b5.png)

**Comment by navjottomer** [comment]
I am not sure what caused it, please check your DB structure and check if all indexes are well defined.
Log slow queries and let me know your findings.

**Comment by eurobank** [comment]
I have disabled the cron's and all plugins and left only the theme (Osclasswizards). And i will monitor after a few hours.

Shall i enable the DB Debug of Osclass? Is that what you mean?

**Comment by navjottomer** [comment]
No not DB-DEBUG
But you'll need full access to MySQL configuration files
See https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html

If the above is not possible then sure to go with this route [Debug SQL](https://docs.mindstellar.com/osclass-docs/developers/basic-osclass/debug-sql-queries) and log your queries, find the slowest queries in them ( in peek time period ) and let me know.

**Comment by eurobank** [comment]
Well i do not have any access to MySQL cfg files. I will go the other way and see what is logged.

If no plugins are active, who is using the hourly cron? Could be the theme? Because i can't disable it, not possible in a live system.

**Comment by navjottomer** [comment]
Osclass does its own maintenance periodically, it is quite stressful on a large database If it's done in a long time.
You can disable the inbuilt-cron.

**Comment by eurobank** [comment]
Ok, after a few hours with CRON disabled, no issues. As soon as i re-enabled CRON the issue is back.

**So it is definitely something that happens with CRON, hourly.**

Now, going to enable also DB debug of Osclass to check.

**Comment by eurobank** [comment]
Enabled dbdebug, nothing is logged, no such file, no errors in debug.log, nothing.

Not sure what to do next, since these are  live/production sites and i must solve this or restore the other release channel backups.

**Comment by navjottomer** [comment]
> Enabled dbdebug, nothing is logged, no such file, no errors in debug.log, nothing.
> 
> Not sure what to do next, since these are live/production sites and i must solve this or restore the other release channel backups.

Did you enabled logging as well?

**Comment by eurobank** [comment]
Actually i was only enabled the log part. My mistake.

**Comment by eurobank** [comment]
I have the logs now, but what shall i look for?

Also i could post the log here, but it is big and i do not really want to publicly post anything.

**Comment by navjottomer** [comment]
make a quick search for `Total queries time:` and check for the section which has the longest time. Don't consider anything below 1 second.
I suspect location stats update cron, it makes thousands of queries and can burden the DB server,  Just look for what I told you and share some logs here after removing sensitive information. 
It'll keep stressing your server until it's not completed.

**Comment by eurobank** [comment]
I will do all that.

I have asked my hosting support for help and they started to monitor. They found something, i will check and update here.

**Comment by eurobank** [comment]
There is nothing above 1 second.

**Comment by navjottomer** [comment]
> There is nothing above 1 second.

How many entries in oc_t_locations_tmp left now?

**Comment by eurobank** [comment]
Showing rows 0 - 24 (143853 total, Query took 0.0004 seconds.)

**Comment by navjottomer** [comment]
Comment out this code and check if the issue still persists.
https://github.com/mindstellar/Osclass/blob/9e13bb58df1df7bba557b1abc20f424dcb29f4ca/oc-includes/osclass/cron.php#L62

like below:
```php
//osc_update_location_stats(true, 'auto');
```

**Comment by eurobank** [comment]
That did help A LOT. 

The peak is much much lower and instead of 25-30 minutes (!!!!) now lasts less than a minute or so.

**Comment by navjottomer** [comment]
Okay, keep it that way, for now, those old queries are not really optimized. will submit new changes to it.
I update this thread with new info.

**Comment by eurobank** [comment]
No problem. Just that i never had this issues with 3.9 or the other release. this issue surfaced with 5.0.2.

Anyways, all good.

**Comment by navjottomer** [comment]
> No problem. Just that i never had these issues with 3.9 or the other release. this issue surfaced with 5.0.2. Same hosting, same plans, same everything.
> 
> Anyways, all good.

Yes, previous releases have issues running cron properly. Location stat code is untouched.

**Comment by navjottomer** [comment]
@eurobank  see this https://github.com/mindstellar/Osclass/commit/7cd02d80795f3a8c441f6627f6d2f48acad80681 commit.
Major improvement in the previous implementation of locations stats modal.

**Comment by eurobank** [comment]
Shall i try it?

**Comment by navjottomer** [comment]
> Shall i try it?

I deployed the changes on these files to my production as improvement was so dramatic almost 100x reduction in MySQL queries. Didn't observed any bug yet after 3-4 hours of testing on the development server.

If you wanna try you can. Attached modified files for 5.0.2, you can try this.
[locationStatsPatch.zip](https://github.com/mindstellar/Osclass/files/7139725/locationStatsPatch.zip)

**Comment by eurobank** [comment]
I will try them to one site, the one with the issue (the big tmp-something fdb table). That one has many many countries (30?).

**Comment by eurobank** [comment]
I did install them but also utils.php that seems missing from the zip you attacked.

Is it ok?

**Comment by navjottomer** [comment]
> I did install them but also utils.php that seems missing from the zip you attacked.
> 
> Is it ok?

make sure this one: `oc-includes/osclass/classes/utility/Utils.php`
Not this one: `oc-includes/osclass/utils.php`

And revert your ` cron.php`  file as it was before.
[locationStatsPatch.zip](https://github.com/mindstellar/Osclass/files/7143379/locationStatsPatch.zip)

**Comment by navjottomer** [comment]
@eurobank does it solved your issue.

**Comment by eurobank** [comment]
@navjottomer I didn't have the time to install and check.

I will update here as soon as i can.

**Comment by eurobank** [comment]
Installing those 5 files have some strange effect in ads publishing. The images show in the final ad are NOT what are uploaded but from some ads previously posted.

**Comment by navjottomer** [comment]
> Installing those 5 files have some strange effect in ads publishing. The images show in the final ad are NOT what are uploaded but from some ads previously posted.

Are you sure? No image related code has been touched see https://github.com/mindstellar/Osclass/commit/7cd02d80795f3a8c441f6627f6d2f48acad80681

And same is working on my website https://tuffclassified.com

**Comment by eurobank** [comment]
I believe you, but this is what i saw. Reverted those 5 files back and all ok.

I will check this to a test site i have and update here. Is anybody else helping on this tests with 5? Why not? Where are all those devs and webmaster ....

**Comment by navjottomer** [comment]
> I believe you, but this is what i saw. Reverted those 5 files back and all ok.
> 
> I will check this to a test site i have and update here. Is anybody else helping on this tests with 5? Why not? Where are all those devs and webmaster ....

There are a few like you.
BTW something strange is happening on your site. I wish I could see by myself.

**Comment by eurobank** [comment]
Yes this specific site from all is stuborn for some reason.

**Comment by eurobank** [comment]
I'm restoring a good back of this morning and start again. Maybe i messed something up, doing several changes in themes plugins and your fixes. Who knows.

**Comment by eurobank** [comment]
Todays stats compared with https://github.com/mindstellar/Osclass/issues/368#issuecomment-914672601

![Screenshot](https://user-images.githubusercontent.com/4467158/132944228-54c81544-c4fa-4d3d-90eb-df198ac9d087.png)

**Comment by navjottomer** [comment]
That looks great I think, it is resolved now, will keep this open till it is not merged in the main branch.

For the PHP parse error, I made that mistake in the files I sent you.  In repo it is correct.

**Comment by eurobank** [comment]
This is a 4 hours stats for ALL sites patches. Looks almost flat for DB usage and that is really great. 

![Screenshot](https://user-images.githubusercontent.com/4467158/132951195-049d44d6-849c-4a35-950e-f2cb1fbffdeb.png)

**Comment by eurobank** [comment]
@navjottomer As you can see in this 24 hours stats, the 1/3 of the day with ONLY the heavy site patched, and the rest with all sites patched, there are NO blue peaks any more.

Great work, imho. thank you.

![Screenshot](https://user-images.githubusercontent.com/4467158/132965829-26202dfa-3b96-4639-93b8-3f5727160b11.png)

**Comment by eurobank** [comment]
@navjottomer probably you may want to close this.
