### ISSUE TITLE
5.0.2 - PHP Fatal error:  Uncaught ImagickDrawException: Unrecognized color string

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#369]
Osclass 5.0.2 and PHP 7.3.x

Trying to setup media settings for fix some watermark text issues, it doesn't seem to work. It crashes with:

[09-Sep-2021 10:06:12 Europe/London] PHP Fatal error:  Uncaught ImagickDrawException: Unrecognized color string in /home/oc-includes/osclass/classes/ImageProcessing.php:584

![Screenshot](https://user-images.githubusercontent.com/4467158/132657854-1b1e88c7-dec9-4590-b5b0-a976961c19cf.png)

**Comment by eurobank** [comment]
And after that error, nobody can post an ad with an image.

**Comment by eurobank** [comment]
This seems correct in the db:

`{"watermark_width":300,"watermark_height":40,"text_offset_x":20,"text_offset_y":20,"text_angle":0,"background_color":"#FFFFFF"}`

**Comment by eurobank** [comment]
The issue is here:

watermark_text_color | ffffff

needs the hex without #

**Comment by eurobank** [comment]
And also the "centre" is not correct, "center" is the correct.

![Screenshot](https://user-images.githubusercontent.com/4467158/132676375-5a993e1c-c8b3-45ae-bdf3-589ed3b6e649.png)

**Comment by navjottomer** [comment]
Those are never meant to be put manually, Issue is colour picker CSS style is not loading, and that's why it is not loading.
https://github.com/mindstellar/Osclass/blob/9e13bb58df1df7bba557b1abc20f424dcb29f4ca/oc-admin/themes/modern/settings/media.php#L33

Change it to
```php
osc_enqueue_style('colorpicker', osc_assets_url('osclass-legacy/js/colorpicker/css/colorpicker.css'));
```

**Comment by eurobank** [comment]
Well as soon as i removed the #, it worked.

**Comment by navjottomer** [comment]
> Well as soon as i removed the #, it worked.

That's what colorpicker do.

**Comment by eurobank** [comment]
ok, so what i see below,  after the fix, is correct or not? because i see manually edit for everything available?

![Screenshot](https://user-images.githubusercontent.com/4467158/132690732-285c67d0-84aa-4b6a-9e61-8e856d3f4e08.png)

**Comment by navjottomer** [comment]
> ok, so what i see below, after the fix, is correct or not? because i see manually edit for everything available? I can put # manually if i want.
> 

That's how it was initially.

in the dev branch, it looks like this

![Screenshot 2021-09-09 190628](https://user-images.githubusercontent.com/1062985/132696185-ca076798-2c86-4255-b14d-ca462f61af40.png)

**Comment by eurobank** [comment]
Great. I'm ok as long as it works for posting users now with the fix.

**Comment by eurobank** [comment]
This functions do NOT work well even with your fix.

When you change and save, the data is wrong. The text color from 000000 becomes 0 for example.

**Comment by eurobank** [comment]
The error is still the same:

PHP Fatal error:  Uncaught ImagickDrawException: Unrecognized color string in /home/oc-includes/osclass/classes/ImageProcessing.php:584

**Comment by eurobank** [comment]
Maybe this will help, after a SAVE, see what a field becomes:

**Comment by navjottomer** [comment]
I may not fix this as it is already fixed in the dev branch. More energy towards finalizing that so we can push a beta soon. 
If in between any maintenance release happen then it'll be fixed, 
Don't close this for now.

**Comment by eurobank** [comment]
ok! This is something like SAVING issue. Wrrong data is saved in wrong db field. The "centre" became "br". "br" as for html break?
