### ISSUE TITLE
5.0.2 - No country (location) in Related, all themes (bender included)

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#371]
I see that in some countries (locations), in related items, there is NO Country displayed.

**I tried also Bender, same issue.**

![Screenshot](https://user-images.githubusercontent.com/4467158/132845691-12c8ff5c-82c7-425a-8286-dfedb827f886.png)

While in the Listings of admin dashboard, is shows well.

![Screenshot (2)](https://user-images.githubusercontent.com/4467158/132845740-1514b77d-83cb-49ab-af94-d21b76bafd65.png)

**Comment by eurobank** [comment]
This seems to happen in multi country sites.

**Comment by eurobank** [comment]
While in Related in ADS pages, the City is show instead of Country.

![Screenshot](https://user-images.githubusercontent.com/4467158/132849247-0b3d3a81-88e4-4ad9-b055-f3d7a1ceb5c2.png)

**Comment by eurobank** [comment]
While it shows correctly in the Item Ad:

![Screenshot](https://user-images.githubusercontent.com/4467158/132849619-be1f8dd8-71b8-43e4-bdc2-8f4c9f48f2a3.png)

**Comment by navjottomer** [comment]
It's not an Osclass issue, osclass provide all the methods, it's up to the theme developer to use them.
Bender theme there is no call to print country in related ads, that's why there is no country.
Use this in item loop
```php
echo (osc_item_country()) ?: '';
```

**Comment by eurobank** [comment]
@navjottomer it was working ok with 3.9 and Osclasspoint 4.4.

Not sure what you say, i do not get it.

**Comment by navjottomer** [comment]
First of all, don't reference Other releases, they are irrelevant here.

If you can Show the code responsible for rendering related ads, please show it.

- In bender-theme, this file is responsible for related ad rendering [loop-single.php](https://github.com/mindstellar/theme-bender/blob/e09b6899e8d91bf2f3fbe1714eee62a2815b5108/loop-single.php ), It didn't have any code to print country. So I am not sure how it was working with 3.9 or any other versions for you.

- Mostly everyone else uses my Related-Ads plugin, other guys you have mentioned shipped it with their theme with layout or CSS changes. 
 
- Few of them may have included their own implementation, of which I have no control.
- It may be possible that some of them included a call for printing listing country, but still, it is not an Osclass bug.
 
- Right now, I didn't have any code in my access which do this and not behaving properly.

**Comment by eurobank** [comment]
@navjottomer 

With all due respect people will want to upgrade from other versions. This is the way it goes.

If osclass 5 has all the plugins and themes needed, please point them to me. I haven't find any.

So it is only logical that people will want to re-use the old plugins and theme, **the way they worked previously.** Otherwise v5 is useless. We can't even buy some new plugin or theme.

Anyways, thanks.

**Comment by navjottomer** [comment]
> @navjottomer
> 
> With all due respect people will want to upgrade from other versions. This is the way it goes.
> 
> If osclass 5 has all the plugins and themes needed, please point them to me. I haven't found any.
> 
> So it is only logical that people will want to re-use the old plugins and theme, **the way they worked previously.** Otherwise v5 is useless. We can't even buy some new plugins or themes.
> 
> Anyways, thanks.

**Few things first:**

- I can't keep old code just for the sake of compatibility which is in dire need of an update, that's the way it goes. If you want to compromise security with compatibility then go with any other release which works better.

- For compatibility, show me the plugin, which was working previously but now has broken and I'll help to fix that. But don't assume I'll fix everything

- I can't do everything Improving osclass, making themes and plugins at the same time. I am working on the project day and night, New translations, new locations, New backend. Everything takes time.

-  My first goal was to redesign the backend and then the inbuilt store, after that any plugin or theme, so you have to wait.

**Anyway for related ads:** 
You said that it was working properly with 3.9 and other releases, but theme bender doesn't even have that code nor osclass than how it is Osclass bug. That's the only point here.

**Comment by eurobank** [comment]
Ok, please point me to the correct theme (bender) that i must use with 5.0.x. So i can test properly. Bender or whatever.

Because we must have a 5 compatible theme to test. Or suggest something else. I dunno.

**Comment by eurobank** [comment]
Also pls note that i'm not a developer, i'm just and experienced webmaster. Sometimes you clearly see and understand things, that webmasters do not. And we shouldn't, not our business. 

Currently i'm struggling to update to Osclass 5 several sites from 3.9 or other releases and i have a very very very hard time. You can't imagine how hard, since we are talking about live/production sites.

**Comment by navjottomer** [comment]
I understand and it is troublesome to do that. For that, you can make a discussion thread here https://github.com/mindstellar/Osclass/discussions and I try to help as much as possible. It'll also keep track of all the issues while upgrading and certainly help others too.

**Comment by eurobank** [comment]
Apologies for that, TRUE some mod was made to both themes from a previous webmaster, to handle multi countries osclass.

Comparing the files, i was that for related and other places.
