### ISSUE TITLE
5.1 beta - Deleting a Plugin

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#381]
Trying to delete a plugin (the link is: javascript:delete_plugin('google_maps/index.php');

i get a blank page, no errors, nothing in debug.log.

PHP 7.4.x and Litespeed server.

**Comment by navjottomer** [comment]
I tried on my site and it did work, check if it is only related to this plugin only. And after error class fix.

**Comment by eurobank** [comment]
No, all plugins. I applied the commints, the issue is there.

Now i see a "false" in the blank page.

**Comment by navjottomer** [comment]
check for any console error in the browser while on the plugin manager page.

**Comment by eurobank** [comment]
> 
> 
> check for any console error in the browser while on the plugin manager page.

I already did, no issues at all. Clean.

BUT i do all my work with Firefox. Trying with Chrome, it works.
