### ISSUE TITLE
Osclass 5.0.2 & 5.1 beta - User listings inconsistency

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#385]
No plugins.

I see a user in my tests with 3 listings
![2021-09-22 01_46_27-Window](https://user-images.githubusercontent.com/4467158/134258836-c27c59e7-0d51-485d-a327-8074eeea1e3d.png)

but there are 2 listings from that user. 

![2021-09-22 01_47_33-Window](https://user-images.githubusercontent.com/4467158/134258866-96dad4d5-f8b8-49a9-8b22-7fc8b2aff95b.png)

isn't the # of items realtime or it is calculated at some time later?

**Comment by eurobank** [comment]
Seems fixed after all the commits i applied.

**Comment by dftd** [comment]
@eurobank Did you delete any items, categories, locations, etc? Upon deletion of those, user item count is recalculated.

**Comment by eurobank** [comment]
Categories and locations no, items maybe the users did? I didn't. 

I will have to check this more, please leave it open for a week or so.
