### ISSUE TITLE
5.1 beta 2: extra fields added to item as new index array

### ISSUE THREAD

**Issue by alastairR** [mindstellar/Osclass#392]
Previously, 5.0.2 the extra fields in Item->extendData were merged into the item array, but in 5.1 they are now added as a sub array indexed by 0. If this was changed to stop existing fields from being overwritten by the extra fields, can the extra fields be added to the item with the key 'extra' instead of 0? This would follow the existing convention of locale.
In the same area, it would probably be a good idea to include custom fields in the extendData function, perhaps added as a sub array with the key 'meta'. That would allow the custom fields to be accessed more easily/efficiently by plugins and themes.

p.s. 5.1 is a really nice piece of work. Congratulations on your effort.

**Comment by navjottomer** [comment]
That was a mistake fixed in 50976bd4166478fcb423e3c2a1dcd6eb5b08e94a

**Comment by navjottomer** [comment]
8d37fd96661094bd19e92232844f01619c6930af
