### ISSUE TITLE
5.1 beta 2: osc_add_admin_menu_page ignores icon_url parameter

### ISSUE THREAD

**Issue by alastairR** [mindstellar/Osclass#393]
When passing the icon_url parameter to AdminMenu->add_menu it resets the icon_url parameter to null. It just needs the assignment removed.

**Comment by navjottomer** [comment]
I am waiting for PR.

**Comment by alastairR** [comment]
Sorry, I was busy with other stuff and my git skills weren't good enough to
extract one file to push.
I'll have another go sometime.
It's a bit annoying because it was just a change to line 214 in
hAdminMenu.php to remove the '= null' for the $icon_url parameter.

**Comment by navjottomer** [comment]
No worry, I'll push it from my end. I thought that you were working on it.
