### ISSUE TITLE
New Dashboard in 5.1 and Listings by category

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#396]
The new design of the dashboard is now taking a huge page in length (down) since it is not now scrollable within a window. This is not good or practical  since on a live site, the Listings by category will be 2-3 pages long (down).

![Screenshot](https://user-images.githubusercontent.com/4467158/134903877-fa1b6936-c709-4534-bf07-336736b8b804.png)

**Comment by navjottomer** [comment]
Yeah, I seen that. It'll be fixed.

**Comment by navjottomer** [comment]
Few adjustments are made.

**Comment by eurobank** [comment]
Fixed indeed.
