### ISSUE TITLE
5.1 beta 2: Scripts and styles not included before 404.php shown

### ISSUE THREAD

**Issue by alastairR** [mindstellar/Osclass#398]
BaseModel does not run print scripts or styles before running the theme 404.php, upsetting layouts dependant on them.

osc_run_hook('before_html');
immediately before 
osc_current_web_theme_path('404.php');
in do400(), do404() and do410() seems to fix it.

**Comment by navjottomer** [comment]
Working fine on my installation.

**Comment by alastairR** [comment]
Sorry, my bad. My theme was structured incorrectly.
