### ISSUE TITLE
s_access_ip IPv6

### ISSUE THREAD

**Issue by Tangol** [mindstellar/Osclass#400]
At the moment, Osclass stores the user access IP as `varchar(15)` which is the standard for IPv4 (15 characters long).
https://github.com/mindstellar/Osclass/blob/master/oc-includes/osclass/installer/struct.sql#L143
https://github.com/mindstellar/Osclass/blob/master/oc-includes/osclass/installer/struct.sql#L126

The question is, what happens when a user accesses the website from an IPv6 address?
Does it get stored/returned correctly?

**Comment by navjottomer** [comment]
Ipv6 get clipped, I have changed it to `varchar(50)` in the recent commit.
