### ISSUE TITLE
 ERROR: Invalid address:  (to): .

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#402]
Is that error something that could create some further issue? A malformed email address, starting with a dot.

2021-09-30 04:29:48 - ERROR: Invalid address:  (to): .23@malaysiatours.ir in /home/public_html/oc-includes/vendor/phpmailer/phpmailer/src/PHPMailer.php on line no 1157 Error Code:0 with context: 
'#0 [internal function]: PHPMailer\\PHPMailer\\PHPMailer->addAnAddress(\'to\', \'.23@malaysiatou...\', \'4837308324\')

**Comment by navjottomer** [comment]
We need to add some checks though, so these addresses do not pass to PHPMailer.
What triggered it?

**Comment by eurobank** [comment]
A new user registration with the email posted above (starting with a dot).

**Comment by navjottomer** [comment]
Okay I see, we're still using old osclass methods for validation, they're not quite accurate in validating emails.  Closing this now as eventually, we'll move on to new validation class methods in the next release anyway.
