### ISSUE TITLE
PHP Notice in v5.0.2

### ISSUE THREAD

**Issue by Tangol** [mindstellar/Osclass#406]
Please note that every action that makes the item post fail, like: _An user has to wait X seconds between each listing added_, or any failed field form validation, causes the following notice:
`PHP Notice:  Trying to access array offset on value of type null in \oc-includes\osclass\classes\form\ItemForm.php on line 135`

Osclass 5.0.2
PHP 7.4.24

**Comment by navjottomer** [comment]
Not able to reproduce it in 5.1 betas.

**Comment by Tangol** [comment]
> Not able to reproduce it in 5.1 betas.

I can't install any of the betas on localhost, PHP 7.4.24
I just get a blank page when I click on **Install** (I'm installing in a subfolder).

**Comment by eurobank** [comment]
https://github.com/mindstellar/Osclass/issues/378
