### ISSUE TITLE
5.1b2 New Installation error

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#420]
After applying this

https://github.com/mindstellar/Osclass/issues/419

the installation starts BUT there is some error:

![Screenshot](https://user-images.githubusercontent.com/4467158/136622112-982e9e52-e1b1-4f14-aab7-aeec39d25a42.png)

**Comment by navjottomer** [comment]
If an issue arises due to the fix of an issue and if it's not old, then it's better to keep the discussion in the same thread.
