### ISSUE TITLE
Install Error: Call to undefined function osc_get_languages_json_url() - install.php on line 64

### ISSUE THREAD

**Issue by AdsTable** [mindstellar/Osclass#433]
When trying to install, it gives such an error:

Uncaught Error: Call to undefined function osc_get_languages_json_url() 
in ..\osclass510b2\oc-includes\osclass\install.php:64 
Stack trace: #0 {main} thrown in ..\osclass510b2\oc-includes\osclass\install.php on line 64

If you comment out 64 line in install.php, 
//"$jsonLocales = osc_file_get_contents(osc_get_languages_json_url());"

then the installation goes - "All right! All the requirements have met"

But on the next step, after creating a new database, new error comes out:
"Can't insert basic configuration. Error number: 1452"

**Comment by navjottomer** [comment]
Try the latest dev branch.
