### ISSUE TITLE
Favicon.ico - Overwrites your own

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#437]
In the archive or auto-update, Osclass overwrites your Favicon.ico and that is not good.

Maybe you could remove that from the release or find some other way, maybe use some other path for it, or whatever.

**Comment by navjottomer** [comment]
We can't remove it from the archive but sure we can fix the overwrite of favicon.ico in auto-updater.

**Comment by eurobank** [comment]
Wordpress archive root doesn't include a favicon.ico, why not move it to the theme directory?

**Comment by navjottomer** [comment]
Most theme developers use different paths to the favicon than the root favicon file. I'll see what I can do, first priorities are for the market.
