### ISSUE TITLE
AjaxUploader not actually throwing exceptions

### ISSUE THREAD

**Issue by dftd** [mindstellar/Osclass#440]
https://github.com/mindstellar/Osclass/blob/070f6f93fc26532cffbc989df72c16f37c3cd330/oc-includes/AjaxUploader.php#L55

No exceptions are thrown, it just returns an error in an array.
This doesn't trigger the try/catch block in ajax controller.

**Comment by navjottomer** [comment]
It only has two lines where this can happen, not all errors throw exceptions.
     https://github.com/mindstellar/Osclass/blob/070f6f93fc26532cffbc989df72c16f37c3cd330/oc-includes/AjaxUploader.php#L63

https://github.com/mindstellar/Osclass/blob/070f6f93fc26532cffbc989df72c16f37c3cd330/oc-includes/AjaxUploader.php#L90

**Comment by dftd** [comment]
But if the image is e.g. too big, the code just continues because an error array is returned and nothing is done with it.

https://github.com/mindstellar/Osclass/blob/070f6f93fc26532cffbc989df72c16f37c3cd330/oc-includes/osclass/classes/controller/CWebAjax.php#L362

**Comment by navjottomer** [comment]
Hmm, that can be fixed.

**Comment by dftd** [comment]
In my api I just made it throw an exception if `isset($result['error'])`.

**Comment by navjottomer** [comment]
create a pull then I'll merge.

**Comment by dftd** [comment]
Can do tomorrow.

**Comment by navjottomer** [comment]
I also request you to help me clean up https://github.com/mindstellar/shopclass as some of the code is legacy and not needed anymore. In your free time if possible.

**Comment by dftd** [comment]
Do you plan to make it the default theme at some point? Not sure how I feel about all the integrated features as a part of a theme.

**Comment by navjottomer** [comment]
Nope, not default just an alternative. Some features need integration in osclass itself and some need removal altogether.  I have created them as some features were not available with osclass nor any plugin was available to provide those features at the time.

**Comment by eurobank** [comment]
@dftd I highly disagree. Plugins will come maybe late and right now a real theme is needed to PROMOTE the use of Osclass of this release channel. 

I think that move from @navjottomer is excellent (to offer this theme for free, since it was NOT free). But apparently need some work to work with 5.1. I can't help coding but i surely can help a lot in testing.

**Comment by eurobank** [comment]
@navjottomer What happened with the Shopclass theme? Freezed?
