### ISSUE TITLE
Show e-mail checkbox is always enabled

### ISSUE THREAD

**Issue by navjottomer** [mindstellar/Osclass#441]
In the new version of the site, the Show e-mail checkbox is always enabled, it cannot be turned off even by the administrator.

_Originally posted by @buninsan in https://github.com/mindstellar/Osclass/discussions/435#discussioncomment-1659984_

**Comment by eurobank** [comment]
@buninsan Does this fix work for you?

**Comment by dftd** [comment]
This fixed the "always enabled" but there's still problems with how value is read from session. For me it now always kept it unchecked.

`if (Session::newInstance()->_getForm('showEmail') != 0)` should _probably_ be `if (Session::newInstance()->_getForm('showEmail') != "")` in `show_email_checkbox`.
