### ISSUE TITLE
Custom field reordering

### ISSUE THREAD

**Issue by dftd** [mindstellar/Osclass#444]
Not sure did we talk about this already or not? I don't see any issues open.

@navjottomer if you're okay with it, I'd go with implementing it, the same way we have category ordering.

**Comment by navjottomer** [comment]
Yeah, You can go implement this. Just make sure to use the Pure JS and new library I used for the category.
I was about to work on that, but I am not sure I'll get any time to proceed before the Osclass market.

**Comment by dftd** [comment]
Having a doubt, what to do when a new field is created?
Do I update every other field to make sure new one is on top, like categories?

When it's deleted? Update every other field so there's no skipped numbers in order? It doesn't really matter though.

**Comment by navjottomer** [comment]
Start with it as you see appropriate, I'll guide if need any improvement.

**Comment by navjottomer** [comment]
How is it working for you?

**Comment by dftd** [comment]
@navjottomer Busy recently... Will try to do it this week.
