### ISSUE TITLE
NOTICE: Undefined indexes in hDefines.php

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#446]
Osclass 5.1dev and PHP 7.4.x

Those (if i remember right) are so old as Osclass script:

2021-11-25 13:37:43 - NOTICE: Undefined index: pk_i_id in /home/oc-includes/osclass/helpers/hDefines.php on line no 586 Error Code:8

2021-11-25 13:37:43 - NOTICE: Undefined index: s_title in /home/oc-includes/osclass/helpers/hDefines.php on line no 588 Error Code:8

2021-11-25 13:37:43 - NOTICE: Undefined index: fk_i_category_id in /home/oc-includes/osclass/helpers/hDefines.php on line no 594 Error Code:8

If i also remember correctly some reply from dev101 in the RIP Osclass forums, those are due to Bing search engine. Not sure if they are.

**Comment by navjottomer** [comment]
I have made some changes, will show a more helpful warning. But really depends on the usage of osc_item_url, osc_premium_url.
If someplace it is showing that, we get to know the full trace to really fix this.

**Comment by eurobank** [comment]
@navjottomer 

After the code changes, i see this:

2021-12-10 11:24:53 - USER_WARNING: Item is not an array or does not have the necessary variables in /home/public_html/oc-includes/osclass/helpers/hDefines.php on line no 615 Error Code:512


Does it help?

**Comment by navjottomer** [comment]
> @navjottomer 
> 
> After the code changes, i see this:
> 
> 2021-12-10 11:24:53 - USER_WARNING: Item is not an array or does not have the necessary variables in /home/public_html/oc-includes/osclass/helpers/hDefines.php on line no 615 Error Code:512
> 
> 
> Does it help?

What was the requested url

**Comment by eurobank** [comment]
How can i find that?

**Comment by navjottomer** [comment]
It should be in error log.

**Comment by eurobank** [comment]
Nope. Nothing else. Just that in the debug log.

I tried using the date and time to find something in the RAW website logs. Hard to find BUT in those time ranges, all i see are some crapy Megaindex.ru hitting heavily.

**Comment by navjottomer** [comment]
Share couple lines of log.

**Comment by eurobank** [comment]
GET /search/region,782051/category,152/sShowAs,gallery/sOrder,dt_pub_date/iOrderType,desc HTTP/1.1" 200 12582 "-" "Mozilla/5.0 (compatible; MegaIndex.ru/2.0;

GET /search/iPage,2/region,782046/category,food-entertainment/sOrder,i_price/iOrderType,asc/sShowAs,gallery

78.46.174.55 - - [10/Dec/2021:06:18:20 -0500] "GET /search/region,782051/category,152/sShowAs,list/sOrder,dt_pub_date/iOrderType,desc

**Comment by eurobank** [comment]
pls do not spend much time and effort on this. it is harmless (after all those years).

**Comment by navjottomer** [comment]
> pls do not spend much time and effort on this. it is harmless (after all those years).


> GET /search/region,782051/category,152/sShowAs,gallery/sOrder,dt_pub_date/iOrderType,desc HTTP/1.1" 200 12582 "-" "Mozilla/5.0 (compatible; MegaIndex.ru/2.0;
> 
> GET /search/iPage,2/region,782046/category,food-entertainment/sOrder,i_price/iOrderType,asc/sShowAs,gallery
> 
> GET /search/region,782051/category,152/sShowAs,list/sOrder,dt_pub_date/iOrderType,desc

Do you get this error on these URLs?
