### ISSUE TITLE
Custom field is not stored when creating new listing

### ISSUE THREAD

**Issue by wadknis** [mindstellar/Osclass#447]
I have a real estate website and when i try to add a new custom field for example " surface" with a text box. When i add a new listing and fill this new custom field. it doesnt appear in item page and as well in the edit item page it shows an empty box like i didn't fill it during adding a new listing.

Check this to have idea what i want to say [https://forums.osclasspoint.com/osclass/custom-field-works-on-item-post-and-not-in-item-page/](url)

**Comment by navjottomer** [comment]
Are you using the osclasspoint release?

**Comment by wadknis** [comment]
> Are you using the osclasspoint release?

I am using 3,8 , By the way i found that custom filed works fine when adding a new listing as a registred member, but not as a guest user. Because i allow users to add listing even they are not registred. How i can resolve that?

**Comment by navjottomer** [comment]
Sorry, we do not support the 3.8 version. Please upgrade to the latest release.
