### ISSUE TITLE
High numbers of concurrent DB connections usage and 'max_user_connections' warning

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#450]
I'm running Osclass 5.2.dev and recently i see a LOT of the following:

WARNING: mysqli::__construct(): (42000/1203): User XXXX already has more than 'max_user_connections' active connections

Now, i also run a Wordpress site in the very same plan, that is much much bigger and heavier (and has a heavy forum plugin). Never seen those warnings.
 
I opened a ticket with my hoster and here is their reply:

"**I suspect you’re not hitting 50 concurrent users as this is actually per database user. It’s a sanity limit. Unless you’re using the same user for all databases or you have some terrible queries it’s unlikely.**"

So i wonder about it. 50 concurrent users for each DB user is truly unlikely to happen in my low traffic site. Could that be some old code or unoptimized something?

**Comment by navjottomer** [comment]
Never seen those on my osclass site, anyway 5.2 dev doesn't have anything added( if I remember correctly) which can lead to this. If this happens with 5.2 then the same could happen with previous releases.
User name which you got in error logs, is this DB user for osclass, WordPress or you are using the same user for both?

**Comment by eurobank** [comment]
No, every site has its own DB user.

**Comment by navjottomer** [comment]
Made a commit, please check if it resolves this.

**Comment by eurobank** [comment]
I will but it takes time, it doesn't happen daily.

**Comment by navjottomer** [comment]
Is it fixed.

**Comment by eurobank** [comment]
It seems so.
