### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Params' not found 

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#452]
OSclass 5.2.0.dev and PHP 7.4

PHP Fatal error:  Uncaught Error: Class 'Params' not found in /home/public_html/index.php:41
Stack trace:
#0 {main}
  thrown in /home/public_html/index.php on line 41

**Comment by navjottomer** [comment]
Couldn't reproduce it and didn't get any warning.

**Comment by eurobank** [comment]
So maybe it was something random, related to something else.

**Comment by navjottomer** [comment]
Most probably a permission issue, but let me know if you found anything.

**Comment by eurobank** [comment]
The only thing is it happened during the upgrade/update from Dashboard. But still, never saw that again or previously. 

Permission issue? I think not. Not in my setup.

**Comment by navjottomer** [comment]
Maybe a random issue then.
