### ISSUE TITLE
Custom Fields are GONE after updated from dev branch

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#466]
No custom Fields anymore after an update i did yesterday from dev branch. 

![Screenshot](https://user-images.githubusercontent.com/4467158/147561841-79e59334-aac2-4866-a412-391335f48762.png)

**Comment by navjottomer** [comment]
Run db update

**Comment by eurobank** [comment]
@navjottomer Please remind me how.

**Comment by eurobank** [comment]
Found it, thanks !!!

**Comment by eurobank** [comment]
For anyone needing this in the future:

`www . website . com/oc-admin/index.php?page=upgrade&action=upgrade-funcs`
