### ISSUE TITLE
Remove logging of item views per day?

### ISSUE THREAD

**Issue by patriksh** [mindstellar/Osclass#472]
I don't see any themes/plugins actually utilizing this feature. Why not just have one row for each item and it contains the total sum?

**Comment by dev-101** [comment]
I use it in my theme.

**Comment by dftd** [comment]
Maybe make it optional? That would be messy, hmmmm...

Glad to see you back btw @dev-101

**Comment by dev-101** [comment]
I never left :)

It's just that I'm simply maintaining few remaining projects (unknown for how long, though).
