### ISSUE TITLE
slug category not save

### ISSUE THREAD

**Issue by mngzir** [mindstellar/Osclass#474]
hi 
slug The category is not saved

**Comment by eurobank** [comment]
https://github.com/mindstellar/Osclass/issues/462

**Comment by eurobank** [comment]
@mngzir Does Delete a category work for you?

It seems categories functions suffer in general.

Just checked and yes, slugs do not save. Here is the video:

https://drive.google.com/file/d/11o-mJP1Q0Hg4YpF1BgpnNOb4WV0OA03A/view?usp=sharing

**Comment by navjottomer** [comment]
It seems it is not an issue with the latest changes.
