### ISSUE TITLE
rtl version

### ISSUE THREAD

**Issue by mngzir** [mindstellar/Osclass#475]
Hello
I am the Persian language developer of osclass
We added the rtl version in 3.7.4 osclass
I try to add in this system 
Help if you have added a function for rtl in the core

**Comment by navjottomer** [comment]
Sorry wrongly tagged this issue.

**Comment by navjottomer** [comment]
Sorry for the late reply, I have been extremely busy in the last 2 months.
We currently don't have any function directly knowing the language direction.
However, you can use this function to get the whole array of current user locale which have information of language direction.
`osc_get_current_user_locale();`

**Comment by mngzir** [comment]
We want to add rtl to the core osclass
Please add the rtl version of Bootstrap to the core 
All languages that are rtl easily supported

I checked the style file but the rtl version of Bootstrap was not included
Which version of Bootstrap do you use?

**Comment by mngzir** [comment]
Bootstrap version 5 supports rtl well, you just need to add the latest version to the core
It is enough to Rtl the core with the function you said osc_get_current_user_locale();
check it
https://getbootstrap.com/docs/5.1/getting-started/rtl/
