### ISSUE TITLE
Expiration of categories not respected

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#479]
**Describe the bug**

All posted ads are Never Expire

**To Reproduce**

Set a short expiration on a new category and post an ad. 

**Expected behavior**

The ad should follow the category or subcategory expiration

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/4467158/160594602-d672d3f0-568b-428e-bea2-46525d1235b4.png)
![Screenshot (2)](https://user-images.githubusercontent.com/4467158/160594624-56f94485-ace5-4156-90fa-e7494248a0e9.png)

**Additional context**

Osclass 5.1.2 and PHP 7.4.x

**Comment by eurobank** [comment]
This is rather strange, some ads posted in the same category, show expiration, some not.
![Screenshot](https://user-images.githubusercontent.com/4467158/160621909-8c1cf946-7e52-45dd-b0fe-0d93d51eeeac.png)

**Comment by eurobank** [comment]
This seems to happens with new created categories. Not 100% sure about it, but something could be wrong with new created cat/subcategories.

**Comment by eurobank** [comment]
Is that an issue or not? Does anybody else have that?

We can't keep this service without expirations. Please verify or not this issue.

**Comment by vijnv** [comment]
Yes, I noticed this as well since upgrading to 5.1.2

**Comment by eurobank** [comment]
@vijnv Since you seem to still care for this project, could you also check this:

**Comment by eurobank** [comment]
Can we have at LEAST this DURATION fixed please?

**It is IMPOSSIBLE to run a site with that terrible bug.**
