### ISSUE TITLE
osc_item_url_from_item and locales

### ISSUE THREAD

**Issue by patriksh** [mindstellar/Osclass#480]
`osc_item_url_from_item` behaves weird with locales.

It uses the second argument, `$locale` and prepends it to the URL.
Why not use it to get the item title in the proper locale?

Replace `osc_sanitizeString(str_replace(',', '-', $item['s_title'])),` with `osc_sanitizeString(str_replace(',', '-', osc_item_title($locale)))`.

There's no need for the locale code in the URL at all imho.

**Comment by navjottomer** [comment]
Do you want show different titles for the same URL to search engine?
