### ISSUE TITLE
Error in semantic url in  premium display

### ISSUE THREAD

**Issue by maxdual** [mindstellar/Osclass#491]
**Error when using {ITEM CITY} IN PREMIUM URLS**
I am creating a premium display with the following code.

```php
 <?php  dms_get_premiums(4); ?>
<?php  if (dms_count_premiums() > 0) { ?>
<div>code display</div>
<?php }?>
<?php }?>
```

**To Reproduce**

Anomaly only plays on premium urls
http://domain.com/category/subcategory/{ITEM_CITY}/adds-example_i1

**Expected behavior**
non-premium url expected behavior

http://domain.com/category/subcategory/city/adds-example_i1

**Screenshots**

**Additional context**

**Comment by navjottomer** [comment]
No issue in my develop branch
